// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: user/v1/user.proto

package userv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_WechatLogin_FullMethodName          = "/user.v1.UserService/WechatLogin"
	UserService_RefreshToken_FullMethodName         = "/user.v1.UserService/RefreshToken"
	UserService_Logout_FullMethodName               = "/user.v1.UserService/Logout"
	UserService_GetFitnessProfile_FullMethodName    = "/user.v1.UserService/GetFitnessProfile"
	UserService_UpdateFitnessProfile_FullMethodName = "/user.v1.UserService/UpdateFitnessProfile"
	UserService_GenerateWorkoutPlan_FullMethodName  = "/user.v1.UserService/GenerateWorkoutPlan"
	UserService_GetWorkoutPlan_FullMethodName       = "/user.v1.UserService/GetWorkoutPlan"
	UserService_CheckIn_FullMethodName              = "/user.v1.UserService/CheckIn"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	WechatLogin(ctx context.Context, in *WechatLoginRequest, opts ...grpc.CallOption) (*WechatLoginResponse, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	GetFitnessProfile(ctx context.Context, in *GetFitnessProfileRequest, opts ...grpc.CallOption) (*GetFitnessProfileResponse, error)
	UpdateFitnessProfile(ctx context.Context, in *UpdateFitnessProfileRequest, opts ...grpc.CallOption) (*UpdateFitnessProfileResponse, error)
	GenerateWorkoutPlan(ctx context.Context, in *GenerateWorkoutPlanRequest, opts ...grpc.CallOption) (*GenerateWorkoutPlanResponse, error)
	GetWorkoutPlan(ctx context.Context, in *GetWorkoutPlanRequest, opts ...grpc.CallOption) (*GetWorkoutPlanResponse, error)
	CheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*CheckInResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) WechatLogin(ctx context.Context, in *WechatLoginRequest, opts ...grpc.CallOption) (*WechatLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WechatLoginResponse)
	err := c.cc.Invoke(ctx, UserService_WechatLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, UserService_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, UserService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetFitnessProfile(ctx context.Context, in *GetFitnessProfileRequest, opts ...grpc.CallOption) (*GetFitnessProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFitnessProfileResponse)
	err := c.cc.Invoke(ctx, UserService_GetFitnessProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateFitnessProfile(ctx context.Context, in *UpdateFitnessProfileRequest, opts ...grpc.CallOption) (*UpdateFitnessProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFitnessProfileResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateFitnessProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GenerateWorkoutPlan(ctx context.Context, in *GenerateWorkoutPlanRequest, opts ...grpc.CallOption) (*GenerateWorkoutPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateWorkoutPlanResponse)
	err := c.cc.Invoke(ctx, UserService_GenerateWorkoutPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetWorkoutPlan(ctx context.Context, in *GetWorkoutPlanRequest, opts ...grpc.CallOption) (*GetWorkoutPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkoutPlanResponse)
	err := c.cc.Invoke(ctx, UserService_GetWorkoutPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*CheckInResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckInResponse)
	err := c.cc.Invoke(ctx, UserService_CheckIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	WechatLogin(context.Context, *WechatLoginRequest) (*WechatLoginResponse, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	GetFitnessProfile(context.Context, *GetFitnessProfileRequest) (*GetFitnessProfileResponse, error)
	UpdateFitnessProfile(context.Context, *UpdateFitnessProfileRequest) (*UpdateFitnessProfileResponse, error)
	GenerateWorkoutPlan(context.Context, *GenerateWorkoutPlanRequest) (*GenerateWorkoutPlanResponse, error)
	GetWorkoutPlan(context.Context, *GetWorkoutPlanRequest) (*GetWorkoutPlanResponse, error)
	CheckIn(context.Context, *CheckInRequest) (*CheckInResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) WechatLogin(context.Context, *WechatLoginRequest) (*WechatLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WechatLogin not implemented")
}
func (UnimplementedUserServiceServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedUserServiceServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedUserServiceServer) GetFitnessProfile(context.Context, *GetFitnessProfileRequest) (*GetFitnessProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFitnessProfile not implemented")
}
func (UnimplementedUserServiceServer) UpdateFitnessProfile(context.Context, *UpdateFitnessProfileRequest) (*UpdateFitnessProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFitnessProfile not implemented")
}
func (UnimplementedUserServiceServer) GenerateWorkoutPlan(context.Context, *GenerateWorkoutPlanRequest) (*GenerateWorkoutPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateWorkoutPlan not implemented")
}
func (UnimplementedUserServiceServer) GetWorkoutPlan(context.Context, *GetWorkoutPlanRequest) (*GetWorkoutPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkoutPlan not implemented")
}
func (UnimplementedUserServiceServer) CheckIn(context.Context, *CheckInRequest) (*CheckInResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckIn not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_WechatLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WechatLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).WechatLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_WechatLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).WechatLogin(ctx, req.(*WechatLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetFitnessProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFitnessProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetFitnessProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetFitnessProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetFitnessProfile(ctx, req.(*GetFitnessProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateFitnessProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFitnessProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateFitnessProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateFitnessProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateFitnessProfile(ctx, req.(*UpdateFitnessProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GenerateWorkoutPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateWorkoutPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GenerateWorkoutPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GenerateWorkoutPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GenerateWorkoutPlan(ctx, req.(*GenerateWorkoutPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetWorkoutPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkoutPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetWorkoutPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetWorkoutPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetWorkoutPlan(ctx, req.(*GetWorkoutPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CheckIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CheckIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CheckIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CheckIn(ctx, req.(*CheckInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WechatLogin",
			Handler:    _UserService_WechatLogin_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _UserService_RefreshToken_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _UserService_Logout_Handler,
		},
		{
			MethodName: "GetFitnessProfile",
			Handler:    _UserService_GetFitnessProfile_Handler,
		},
		{
			MethodName: "UpdateFitnessProfile",
			Handler:    _UserService_UpdateFitnessProfile_Handler,
		},
		{
			MethodName: "GenerateWorkoutPlan",
			Handler:    _UserService_GenerateWorkoutPlan_Handler,
		},
		{
			MethodName: "GetWorkoutPlan",
			Handler:    _UserService_GetWorkoutPlan_Handler,
		},
		{
			MethodName: "CheckIn",
			Handler:    _UserService_CheckIn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/v1/user.proto",
}
