// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: content/v1/content.proto

package contentv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationContentServiceGetEquipment = "/content.v1.ContentService/GetEquipment"
const OperationContentServiceGetExercise = "/content.v1.ContentService/GetExercise"
const OperationContentServiceRecommendExercises = "/content.v1.ContentService/RecommendExercises"

type ContentServiceHTTPServer interface {
	GetEquipment(context.Context, *GetEquipmentRequest) (*GetEquipmentResponse, error)
	GetExercise(context.Context, *GetExerciseRequest) (*GetExerciseResponse, error)
	RecommendExercises(context.Context, *RecommendExercisesRequest) (*RecommendExercisesResponse, error)
}

func RegisterContentServiceHTTPServer(s *http.Server, srv ContentServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/equipment/{equipment_code}", _ContentService_GetEquipment0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/equipment/{equipment_code}/exercises", _ContentService_RecommendExercises0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/exercises/{exercise_code}", _ContentService_GetExercise0_HTTP_Handler(srv))
}

func _ContentService_GetEquipment0_HTTP_Handler(srv ContentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetEquipmentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContentServiceGetEquipment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetEquipment(ctx, req.(*GetEquipmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetEquipmentResponse)
		return ctx.Result(200, reply)
	}
}

func _ContentService_RecommendExercises0_HTTP_Handler(srv ContentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RecommendExercisesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContentServiceRecommendExercises)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RecommendExercises(ctx, req.(*RecommendExercisesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RecommendExercisesResponse)
		return ctx.Result(200, reply)
	}
}

func _ContentService_GetExercise0_HTTP_Handler(srv ContentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetExerciseRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContentServiceGetExercise)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetExercise(ctx, req.(*GetExerciseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetExerciseResponse)
		return ctx.Result(200, reply)
	}
}

type ContentServiceHTTPClient interface {
	GetEquipment(ctx context.Context, req *GetEquipmentRequest, opts ...http.CallOption) (rsp *GetEquipmentResponse, err error)
	GetExercise(ctx context.Context, req *GetExerciseRequest, opts ...http.CallOption) (rsp *GetExerciseResponse, err error)
	RecommendExercises(ctx context.Context, req *RecommendExercisesRequest, opts ...http.CallOption) (rsp *RecommendExercisesResponse, err error)
}

type ContentServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewContentServiceHTTPClient(client *http.Client) ContentServiceHTTPClient {
	return &ContentServiceHTTPClientImpl{client}
}

func (c *ContentServiceHTTPClientImpl) GetEquipment(ctx context.Context, in *GetEquipmentRequest, opts ...http.CallOption) (*GetEquipmentResponse, error) {
	var out GetEquipmentResponse
	pattern := "/v1/equipment/{equipment_code}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationContentServiceGetEquipment),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ContentServiceHTTPClientImpl) GetExercise(ctx context.Context, in *GetExerciseRequest, opts ...http.CallOption) (*GetExerciseResponse, error) {
	var out GetExerciseResponse
	pattern := "/v1/exercises/{exercise_code}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationContentServiceGetExercise),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ContentServiceHTTPClientImpl) RecommendExercises(ctx context.Context, in *RecommendExercisesRequest, opts ...http.CallOption) (*RecommendExercisesResponse, error) {
	var out RecommendExercisesResponse
	pattern := "/v1/equipment/{equipment_code}/exercises"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationContentServiceRecommendExercises),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
