// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: content/v1/content.proto

package contentv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Equipment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EquipmentCode string                 `protobuf:"bytes,1,opt,name=equipment_code,json=equipmentCode,proto3" json:"equipment_code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TargetMuscles []string               `protobuf:"bytes,4,rep,name=target_muscles,json=targetMuscles,proto3" json:"target_muscles,omitempty"`
	SafetyTips    []string               `protobuf:"bytes,5,rep,name=safety_tips,json=safetyTips,proto3" json:"safety_tips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Equipment) Reset() {
	*x = Equipment{}
	mi := &file_content_v1_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Equipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Equipment) ProtoMessage() {}

func (x *Equipment) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Equipment.ProtoReflect.Descriptor instead.
func (*Equipment) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{0}
}

func (x *Equipment) GetEquipmentCode() string {
	if x != nil {
		return x.EquipmentCode
	}
	return ""
}

func (x *Equipment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Equipment) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Equipment) GetTargetMuscles() []string {
	if x != nil {
		return x.TargetMuscles
	}
	return nil
}

func (x *Equipment) GetSafetyTips() []string {
	if x != nil {
		return x.SafetyTips
	}
	return nil
}

type Exercise struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ExerciseCode        string                 `protobuf:"bytes,1,opt,name=exercise_code,json=exerciseCode,proto3" json:"exercise_code,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	EquipmentCode       string                 `protobuf:"bytes,3,opt,name=equipment_code,json=equipmentCode,proto3" json:"equipment_code,omitempty"`
	InstructionVideoUri string                 `protobuf:"bytes,4,opt,name=instruction_video_uri,json=instructionVideoUri,proto3" json:"instruction_video_uri,omitempty"`
	TargetMuscles       []string               `protobuf:"bytes,5,rep,name=target_muscles,json=targetMuscles,proto3" json:"target_muscles,omitempty"`
	KeyPoints           []string               `protobuf:"bytes,6,rep,name=key_points,json=keyPoints,proto3" json:"key_points,omitempty"`
	CommonMistakes      []string               `protobuf:"bytes,7,rep,name=common_mistakes,json=commonMistakes,proto3" json:"common_mistakes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Exercise) Reset() {
	*x = Exercise{}
	mi := &file_content_v1_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exercise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exercise) ProtoMessage() {}

func (x *Exercise) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exercise.ProtoReflect.Descriptor instead.
func (*Exercise) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{1}
}

func (x *Exercise) GetExerciseCode() string {
	if x != nil {
		return x.ExerciseCode
	}
	return ""
}

func (x *Exercise) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Exercise) GetEquipmentCode() string {
	if x != nil {
		return x.EquipmentCode
	}
	return ""
}

func (x *Exercise) GetInstructionVideoUri() string {
	if x != nil {
		return x.InstructionVideoUri
	}
	return ""
}

func (x *Exercise) GetTargetMuscles() []string {
	if x != nil {
		return x.TargetMuscles
	}
	return nil
}

func (x *Exercise) GetKeyPoints() []string {
	if x != nil {
		return x.KeyPoints
	}
	return nil
}

func (x *Exercise) GetCommonMistakes() []string {
	if x != nil {
		return x.CommonMistakes
	}
	return nil
}

type GetEquipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EquipmentCode string                 `protobuf:"bytes,1,opt,name=equipment_code,json=equipmentCode,proto3" json:"equipment_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEquipmentRequest) Reset() {
	*x = GetEquipmentRequest{}
	mi := &file_content_v1_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEquipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEquipmentRequest) ProtoMessage() {}

func (x *GetEquipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEquipmentRequest.ProtoReflect.Descriptor instead.
func (*GetEquipmentRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{2}
}

func (x *GetEquipmentRequest) GetEquipmentCode() string {
	if x != nil {
		return x.EquipmentCode
	}
	return ""
}

type GetEquipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Equipment     *Equipment             `protobuf:"bytes,1,opt,name=equipment,proto3" json:"equipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEquipmentResponse) Reset() {
	*x = GetEquipmentResponse{}
	mi := &file_content_v1_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEquipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEquipmentResponse) ProtoMessage() {}

func (x *GetEquipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEquipmentResponse.ProtoReflect.Descriptor instead.
func (*GetEquipmentResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{3}
}

func (x *GetEquipmentResponse) GetEquipment() *Equipment {
	if x != nil {
		return x.Equipment
	}
	return nil
}

type RecommendExercisesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EquipmentCode string                 `protobuf:"bytes,1,opt,name=equipment_code,json=equipmentCode,proto3" json:"equipment_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendExercisesRequest) Reset() {
	*x = RecommendExercisesRequest{}
	mi := &file_content_v1_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendExercisesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendExercisesRequest) ProtoMessage() {}

func (x *RecommendExercisesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendExercisesRequest.ProtoReflect.Descriptor instead.
func (*RecommendExercisesRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{4}
}

func (x *RecommendExercisesRequest) GetEquipmentCode() string {
	if x != nil {
		return x.EquipmentCode
	}
	return ""
}

type RecommendExercisesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exercises     []*Exercise            `protobuf:"bytes,1,rep,name=exercises,proto3" json:"exercises,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendExercisesResponse) Reset() {
	*x = RecommendExercisesResponse{}
	mi := &file_content_v1_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendExercisesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendExercisesResponse) ProtoMessage() {}

func (x *RecommendExercisesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendExercisesResponse.ProtoReflect.Descriptor instead.
func (*RecommendExercisesResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{5}
}

func (x *RecommendExercisesResponse) GetExercises() []*Exercise {
	if x != nil {
		return x.Exercises
	}
	return nil
}

type GetExerciseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseCode  string                 `protobuf:"bytes,1,opt,name=exercise_code,json=exerciseCode,proto3" json:"exercise_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExerciseRequest) Reset() {
	*x = GetExerciseRequest{}
	mi := &file_content_v1_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExerciseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExerciseRequest) ProtoMessage() {}

func (x *GetExerciseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExerciseRequest.ProtoReflect.Descriptor instead.
func (*GetExerciseRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{6}
}

func (x *GetExerciseRequest) GetExerciseCode() string {
	if x != nil {
		return x.ExerciseCode
	}
	return ""
}

type GetExerciseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exercise      *Exercise              `protobuf:"bytes,1,opt,name=exercise,proto3" json:"exercise,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExerciseResponse) Reset() {
	*x = GetExerciseResponse{}
	mi := &file_content_v1_content_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExerciseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExerciseResponse) ProtoMessage() {}

func (x *GetExerciseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExerciseResponse.ProtoReflect.Descriptor instead.
func (*GetExerciseResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{7}
}

func (x *GetExerciseResponse) GetExercise() *Exercise {
	if x != nil {
		return x.Exercise
	}
	return nil
}

var File_content_v1_content_proto protoreflect.FileDescriptor

const file_content_v1_content_proto_rawDesc = "" +
	"\n" +
	"\x18content/v1/content.proto\x12\n" +
	"content.v1\x1a\x1cgoogle/api/annotations.proto\"\xb0\x01\n" +
	"\tEquipment\x12%\n" +
	"\x0eequipment_code\x18\x01 \x01(\tR\requipmentCode\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12%\n" +
	"\x0etarget_muscles\x18\x04 \x03(\tR\rtargetMuscles\x12\x1f\n" +
	"\vsafety_tips\x18\x05 \x03(\tR\n" +
	"safetyTips\"\x8d\x02\n" +
	"\bExercise\x12#\n" +
	"\rexercise_code\x18\x01 \x01(\tR\fexerciseCode\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0eequipment_code\x18\x03 \x01(\tR\requipmentCode\x122\n" +
	"\x15instruction_video_uri\x18\x04 \x01(\tR\x13instructionVideoUri\x12%\n" +
	"\x0etarget_muscles\x18\x05 \x03(\tR\rtargetMuscles\x12\x1d\n" +
	"\n" +
	"key_points\x18\x06 \x03(\tR\tkeyPoints\x12'\n" +
	"\x0fcommon_mistakes\x18\a \x03(\tR\x0ecommonMistakes\"<\n" +
	"\x13GetEquipmentRequest\x12%\n" +
	"\x0eequipment_code\x18\x01 \x01(\tR\requipmentCode\"K\n" +
	"\x14GetEquipmentResponse\x123\n" +
	"\tequipment\x18\x01 \x01(\v2\x15.content.v1.EquipmentR\tequipment\"B\n" +
	"\x19RecommendExercisesRequest\x12%\n" +
	"\x0eequipment_code\x18\x01 \x01(\tR\requipmentCode\"P\n" +
	"\x1aRecommendExercisesResponse\x122\n" +
	"\texercises\x18\x01 \x03(\v2\x14.content.v1.ExerciseR\texercises\"9\n" +
	"\x12GetExerciseRequest\x12#\n" +
	"\rexercise_code\x18\x01 \x01(\tR\fexerciseCode\"G\n" +
	"\x13GetExerciseResponse\x120\n" +
	"\bexercise\x18\x01 \x01(\v2\x14.content.v1.ExerciseR\bexercise2\x9a\x03\n" +
	"\x0eContentService\x12y\n" +
	"\fGetEquipment\x12\x1f.content.v1.GetEquipmentRequest\x1a .content.v1.GetEquipmentResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/equipment/{equipment_code}\x12\x95\x01\n" +
	"\x12RecommendExercises\x12%.content.v1.RecommendExercisesRequest\x1a&.content.v1.RecommendExercisesResponse\"0\x82\xd3\xe4\x93\x02*\x12(/v1/equipment/{equipment_code}/exercises\x12u\n" +
	"\vGetExercise\x12\x1e.content.v1.GetExerciseRequest\x1a\x1f.content.v1.GetExerciseResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/exercises/{exercise_code}B<Z:github.com/tiehu-ai/tiehu-fitness/api/content/v1;contentv1b\x06proto3"

var (
	file_content_v1_content_proto_rawDescOnce sync.Once
	file_content_v1_content_proto_rawDescData []byte
)

func file_content_v1_content_proto_rawDescGZIP() []byte {
	file_content_v1_content_proto_rawDescOnce.Do(func() {
		file_content_v1_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_content_v1_content_proto_rawDesc), len(file_content_v1_content_proto_rawDesc)))
	})
	return file_content_v1_content_proto_rawDescData
}

var file_content_v1_content_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_content_v1_content_proto_goTypes = []any{
	(*Equipment)(nil),                  // 0: content.v1.Equipment
	(*Exercise)(nil),                   // 1: content.v1.Exercise
	(*GetEquipmentRequest)(nil),        // 2: content.v1.GetEquipmentRequest
	(*GetEquipmentResponse)(nil),       // 3: content.v1.GetEquipmentResponse
	(*RecommendExercisesRequest)(nil),  // 4: content.v1.RecommendExercisesRequest
	(*RecommendExercisesResponse)(nil), // 5: content.v1.RecommendExercisesResponse
	(*GetExerciseRequest)(nil),         // 6: content.v1.GetExerciseRequest
	(*GetExerciseResponse)(nil),        // 7: content.v1.GetExerciseResponse
}
var file_content_v1_content_proto_depIdxs = []int32{
	0, // 0: content.v1.GetEquipmentResponse.equipment:type_name -> content.v1.Equipment
	1, // 1: content.v1.RecommendExercisesResponse.exercises:type_name -> content.v1.Exercise
	1, // 2: content.v1.GetExerciseResponse.exercise:type_name -> content.v1.Exercise
	2, // 3: content.v1.ContentService.GetEquipment:input_type -> content.v1.GetEquipmentRequest
	4, // 4: content.v1.ContentService.RecommendExercises:input_type -> content.v1.RecommendExercisesRequest
	6, // 5: content.v1.ContentService.GetExercise:input_type -> content.v1.GetExerciseRequest
	3, // 6: content.v1.ContentService.GetEquipment:output_type -> content.v1.GetEquipmentResponse
	5, // 7: content.v1.ContentService.RecommendExercises:output_type -> content.v1.RecommendExercisesResponse
	7, // 8: content.v1.ContentService.GetExercise:output_type -> content.v1.GetExerciseResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_content_v1_content_proto_init() }
func file_content_v1_content_proto_init() {
	if File_content_v1_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_content_v1_content_proto_rawDesc), len(file_content_v1_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_content_v1_content_proto_goTypes,
		DependencyIndexes: file_content_v1_content_proto_depIdxs,
		MessageInfos:      file_content_v1_content_proto_msgTypes,
	}.Build()
	File_content_v1_content_proto = out.File
	file_content_v1_content_proto_goTypes = nil
	file_content_v1_content_proto_depIdxs = nil
}
