// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: meeting/v1/meeting.proto

package meetingv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MeetingStatus 表示会议业务生命周期。
type MeetingStatus int32

const (
	// 未指定会议状态。
	MeetingStatus_MEETING_STATUS_UNSPECIFIED MeetingStatus = 0
	// 正在录制并接收实时音频。
	MeetingStatus_MEETING_STATUS_RECORDING MeetingStatus = 1
	// 已停止录音，后续处理尚未全部完成。
	MeetingStatus_MEETING_STATUS_PROCESSING MeetingStatus = 2
	// 转写和后续产物均已完成。
	MeetingStatus_MEETING_STATUS_COMPLETED MeetingStatus = 3
	// 部分产物成功，可针对失败阶段重试。
	MeetingStatus_MEETING_STATUS_PARTIALLY_COMPLETED MeetingStatus = 4
	// 没有可用的最终转写。
	MeetingStatus_MEETING_STATUS_FAILED MeetingStatus = 5
	// 会议在录制阶段被取消。
	MeetingStatus_MEETING_STATUS_CANCELLED MeetingStatus = 6
)

// Enum value maps for MeetingStatus.
var (
	MeetingStatus_name = map[int32]string{
		0: "MEETING_STATUS_UNSPECIFIED",
		1: "MEETING_STATUS_RECORDING",
		2: "MEETING_STATUS_PROCESSING",
		3: "MEETING_STATUS_COMPLETED",
		4: "MEETING_STATUS_PARTIALLY_COMPLETED",
		5: "MEETING_STATUS_FAILED",
		6: "MEETING_STATUS_CANCELLED",
	}
	MeetingStatus_value = map[string]int32{
		"MEETING_STATUS_UNSPECIFIED":         0,
		"MEETING_STATUS_RECORDING":           1,
		"MEETING_STATUS_PROCESSING":          2,
		"MEETING_STATUS_COMPLETED":           3,
		"MEETING_STATUS_PARTIALLY_COMPLETED": 4,
		"MEETING_STATUS_FAILED":              5,
		"MEETING_STATUS_CANCELLED":           6,
	}
)

func (x MeetingStatus) Enum() *MeetingStatus {
	p := new(MeetingStatus)
	*p = x
	return p
}

func (x MeetingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MeetingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_meeting_v1_meeting_proto_enumTypes[0].Descriptor()
}

func (MeetingStatus) Type() protoreflect.EnumType {
	return &file_meeting_v1_meeting_proto_enumTypes[0]
}

func (x MeetingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MeetingStatus.Descriptor instead.
func (MeetingStatus) EnumDescriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{0}
}

// TranscriptionStatus 表示一次会议的实时转写阶段。
type TranscriptionStatus int32

const (
	// 未指定转写状态。
	TranscriptionStatus_TRANSCRIPTION_STATUS_UNSPECIFIED TranscriptionStatus = 0
	// 等待 vision-service 准备转写会话。
	TranscriptionStatus_TRANSCRIPTION_STATUS_PENDING TranscriptionStatus = 1
	// 正在建立业务和 Provider 连接。
	TranscriptionStatus_TRANSCRIPTION_STATUS_CONNECTING TranscriptionStatus = 2
	// 正在接收音频并返回实时文本。
	TranscriptionStatus_TRANSCRIPTION_STATUS_STREAMING TranscriptionStatus = 3
	// 已停止接收新音频，正在刷新尾部结果。
	TranscriptionStatus_TRANSCRIPTION_STATUS_FINISHING TranscriptionStatus = 4
	// 最终转写已完成。
	TranscriptionStatus_TRANSCRIPTION_STATUS_SUCCEEDED TranscriptionStatus = 5
	// 转写失败。
	TranscriptionStatus_TRANSCRIPTION_STATUS_FAILED TranscriptionStatus = 6
	// 转写由用户或服务取消。
	TranscriptionStatus_TRANSCRIPTION_STATUS_CANCELLED TranscriptionStatus = 7
	// 转写会话因超时过期。
	TranscriptionStatus_TRANSCRIPTION_STATUS_EXPIRED TranscriptionStatus = 8
)

// Enum value maps for TranscriptionStatus.
var (
	TranscriptionStatus_name = map[int32]string{
		0: "TRANSCRIPTION_STATUS_UNSPECIFIED",
		1: "TRANSCRIPTION_STATUS_PENDING",
		2: "TRANSCRIPTION_STATUS_CONNECTING",
		3: "TRANSCRIPTION_STATUS_STREAMING",
		4: "TRANSCRIPTION_STATUS_FINISHING",
		5: "TRANSCRIPTION_STATUS_SUCCEEDED",
		6: "TRANSCRIPTION_STATUS_FAILED",
		7: "TRANSCRIPTION_STATUS_CANCELLED",
		8: "TRANSCRIPTION_STATUS_EXPIRED",
	}
	TranscriptionStatus_value = map[string]int32{
		"TRANSCRIPTION_STATUS_UNSPECIFIED": 0,
		"TRANSCRIPTION_STATUS_PENDING":     1,
		"TRANSCRIPTION_STATUS_CONNECTING":  2,
		"TRANSCRIPTION_STATUS_STREAMING":   3,
		"TRANSCRIPTION_STATUS_FINISHING":   4,
		"TRANSCRIPTION_STATUS_SUCCEEDED":   5,
		"TRANSCRIPTION_STATUS_FAILED":      6,
		"TRANSCRIPTION_STATUS_CANCELLED":   7,
		"TRANSCRIPTION_STATUS_EXPIRED":     8,
	}
)

func (x TranscriptionStatus) Enum() *TranscriptionStatus {
	p := new(TranscriptionStatus)
	*p = x
	return p
}

func (x TranscriptionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TranscriptionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_meeting_v1_meeting_proto_enumTypes[1].Descriptor()
}

func (TranscriptionStatus) Type() protoreflect.EnumType {
	return &file_meeting_v1_meeting_proto_enumTypes[1]
}

func (x TranscriptionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TranscriptionStatus.Descriptor instead.
func (TranscriptionStatus) EnumDescriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{1}
}

// MeetingSummaryStatus 表示会议纪要的异步生成阶段。
type MeetingSummaryStatus int32

const (
	// 未指定纪要状态。
	MeetingSummaryStatus_MEETING_SUMMARY_STATUS_UNSPECIFIED MeetingSummaryStatus = 0
	// 当前会议尚未提交纪要任务。
	MeetingSummaryStatus_MEETING_SUMMARY_STATUS_NOT_STARTED MeetingSummaryStatus = 1
	// 纪要任务已经提交并等待处理。
	MeetingSummaryStatus_MEETING_SUMMARY_STATUS_PENDING MeetingSummaryStatus = 2
	// LLM Provider 正在生成纪要。
	MeetingSummaryStatus_MEETING_SUMMARY_STATUS_PROCESSING MeetingSummaryStatus = 3
	// 最新纪要版本生成成功。
	MeetingSummaryStatus_MEETING_SUMMARY_STATUS_SUCCEEDED MeetingSummaryStatus = 4
	// 最新纪要版本生成失败，可以重试。
	MeetingSummaryStatus_MEETING_SUMMARY_STATUS_FAILED MeetingSummaryStatus = 5
)

// Enum value maps for MeetingSummaryStatus.
var (
	MeetingSummaryStatus_name = map[int32]string{
		0: "MEETING_SUMMARY_STATUS_UNSPECIFIED",
		1: "MEETING_SUMMARY_STATUS_NOT_STARTED",
		2: "MEETING_SUMMARY_STATUS_PENDING",
		3: "MEETING_SUMMARY_STATUS_PROCESSING",
		4: "MEETING_SUMMARY_STATUS_SUCCEEDED",
		5: "MEETING_SUMMARY_STATUS_FAILED",
	}
	MeetingSummaryStatus_value = map[string]int32{
		"MEETING_SUMMARY_STATUS_UNSPECIFIED": 0,
		"MEETING_SUMMARY_STATUS_NOT_STARTED": 1,
		"MEETING_SUMMARY_STATUS_PENDING":     2,
		"MEETING_SUMMARY_STATUS_PROCESSING":  3,
		"MEETING_SUMMARY_STATUS_SUCCEEDED":   4,
		"MEETING_SUMMARY_STATUS_FAILED":      5,
	}
)

func (x MeetingSummaryStatus) Enum() *MeetingSummaryStatus {
	p := new(MeetingSummaryStatus)
	*p = x
	return p
}

func (x MeetingSummaryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MeetingSummaryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_meeting_v1_meeting_proto_enumTypes[2].Descriptor()
}

func (MeetingSummaryStatus) Type() protoreflect.EnumType {
	return &file_meeting_v1_meeting_proto_enumTypes[2]
}

func (x MeetingSummaryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MeetingSummaryStatus.Descriptor instead.
func (MeetingSummaryStatus) EnumDescriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{2}
}

// MeetingActionItemStatus 表示会议待办事项的初始处理状态。
type MeetingActionItemStatus int32

const (
	// 尚未指定待办状态。
	MeetingActionItemStatus_MEETING_ACTION_ITEM_STATUS_UNSPECIFIED MeetingActionItemStatus = 0
	// 待办事项尚未处理。
	MeetingActionItemStatus_MEETING_ACTION_ITEM_STATUS_PENDING MeetingActionItemStatus = 1
)

// Enum value maps for MeetingActionItemStatus.
var (
	MeetingActionItemStatus_name = map[int32]string{
		0: "MEETING_ACTION_ITEM_STATUS_UNSPECIFIED",
		1: "MEETING_ACTION_ITEM_STATUS_PENDING",
	}
	MeetingActionItemStatus_value = map[string]int32{
		"MEETING_ACTION_ITEM_STATUS_UNSPECIFIED": 0,
		"MEETING_ACTION_ITEM_STATUS_PENDING":     1,
	}
)

func (x MeetingActionItemStatus) Enum() *MeetingActionItemStatus {
	p := new(MeetingActionItemStatus)
	*p = x
	return p
}

func (x MeetingActionItemStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MeetingActionItemStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_meeting_v1_meeting_proto_enumTypes[3].Descriptor()
}

func (MeetingActionItemStatus) Type() protoreflect.EnumType {
	return &file_meeting_v1_meeting_proto_enumTypes[3]
}

func (x MeetingActionItemStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MeetingActionItemStatus.Descriptor instead.
func (MeetingActionItemStatus) EnumDescriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{3}
}

// MeetingLanguage 表示用户选择的会议识别语言。
type MeetingLanguage int32

const (
	// 未指定语言。
	MeetingLanguage_MEETING_LANGUAGE_UNSPECIFIED MeetingLanguage = 0
	// 由 ASR 自动识别语言。
	MeetingLanguage_MEETING_LANGUAGE_AUTO MeetingLanguage = 1
	// 简体中文或中文为主的中英混合会议。
	MeetingLanguage_MEETING_LANGUAGE_ZH_CN MeetingLanguage = 2
	// 英语会议。
	MeetingLanguage_MEETING_LANGUAGE_EN_US MeetingLanguage = 3
)

// Enum value maps for MeetingLanguage.
var (
	MeetingLanguage_name = map[int32]string{
		0: "MEETING_LANGUAGE_UNSPECIFIED",
		1: "MEETING_LANGUAGE_AUTO",
		2: "MEETING_LANGUAGE_ZH_CN",
		3: "MEETING_LANGUAGE_EN_US",
	}
	MeetingLanguage_value = map[string]int32{
		"MEETING_LANGUAGE_UNSPECIFIED": 0,
		"MEETING_LANGUAGE_AUTO":        1,
		"MEETING_LANGUAGE_ZH_CN":       2,
		"MEETING_LANGUAGE_EN_US":       3,
	}
)

func (x MeetingLanguage) Enum() *MeetingLanguage {
	p := new(MeetingLanguage)
	*p = x
	return p
}

func (x MeetingLanguage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MeetingLanguage) Descriptor() protoreflect.EnumDescriptor {
	return file_meeting_v1_meeting_proto_enumTypes[4].Descriptor()
}

func (MeetingLanguage) Type() protoreflect.EnumType {
	return &file_meeting_v1_meeting_proto_enumTypes[4]
}

func (x MeetingLanguage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MeetingLanguage.Descriptor instead.
func (MeetingLanguage) EnumDescriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{4}
}

// AudioFormat 表示实时音频的编码格式。
type AudioFormat int32

const (
	// 未指定音频格式。
	AudioFormat_AUDIO_FORMAT_UNSPECIFIED AudioFormat = 0
	// 有符号 16 bit little-endian 裸 PCM。
	AudioFormat_AUDIO_FORMAT_PCM_S16LE AudioFormat = 1
)

// Enum value maps for AudioFormat.
var (
	AudioFormat_name = map[int32]string{
		0: "AUDIO_FORMAT_UNSPECIFIED",
		1: "AUDIO_FORMAT_PCM_S16LE",
	}
	AudioFormat_value = map[string]int32{
		"AUDIO_FORMAT_UNSPECIFIED": 0,
		"AUDIO_FORMAT_PCM_S16LE":   1,
	}
)

func (x AudioFormat) Enum() *AudioFormat {
	p := new(AudioFormat)
	*p = x
	return p
}

func (x AudioFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_meeting_v1_meeting_proto_enumTypes[5].Descriptor()
}

func (AudioFormat) Type() protoreflect.EnumType {
	return &file_meeting_v1_meeting_proto_enumTypes[5]
}

func (x AudioFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioFormat.Descriptor instead.
func (AudioFormat) EnumDescriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{5}
}

// CreateMeetingRequest 是创建会议参数。
type CreateMeetingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 识别语言偏好。
	Language MeetingLanguage `protobuf:"varint,1,opt,name=language,proto3,enum=meeting.v1.MeetingLanguage" json:"language,omitempty"`
	// 是否在识别完成后继续保留云端原始录音。
	RetainAudio bool `protobuf:"varint,2,opt,name=retain_audio,json=retainAudio,proto3" json:"retain_audio,omitempty"`
	// 用户是否明确同意把音频发送到云端处理；必须为 true。
	TranscriptionConsent bool `protobuf:"varint,3,opt,name=transcription_consent,json=transcriptionConsent,proto3" json:"transcription_consent,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateMeetingRequest) Reset() {
	*x = CreateMeetingRequest{}
	mi := &file_meeting_v1_meeting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeetingRequest) ProtoMessage() {}

func (x *CreateMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeetingRequest.ProtoReflect.Descriptor instead.
func (*CreateMeetingRequest) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMeetingRequest) GetLanguage() MeetingLanguage {
	if x != nil {
		return x.Language
	}
	return MeetingLanguage_MEETING_LANGUAGE_UNSPECIFIED
}

func (x *CreateMeetingRequest) GetRetainAudio() bool {
	if x != nil {
		return x.RetainAudio
	}
	return false
}

func (x *CreateMeetingRequest) GetTranscriptionConsent() bool {
	if x != nil {
		return x.TranscriptionConsent
	}
	return false
}

// CreateMeetingResponse 返回会议和短期实时转写连接参数。
type CreateMeetingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 新建或由相同幂等键命中的会议。
	Meeting *Meeting `protobuf:"bytes,1,opt,name=meeting,proto3" json:"meeting,omitempty"`
	// vision-service 签发的一次性实时转写会话。
	TranscriptionSession *TranscriptionSession `protobuf:"bytes,2,opt,name=transcription_session,json=transcriptionSession,proto3" json:"transcription_session,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateMeetingResponse) Reset() {
	*x = CreateMeetingResponse{}
	mi := &file_meeting_v1_meeting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMeetingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeetingResponse) ProtoMessage() {}

func (x *CreateMeetingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeetingResponse.ProtoReflect.Descriptor instead.
func (*CreateMeetingResponse) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMeetingResponse) GetMeeting() *Meeting {
	if x != nil {
		return x.Meeting
	}
	return nil
}

func (x *CreateMeetingResponse) GetTranscriptionSession() *TranscriptionSession {
	if x != nil {
		return x.TranscriptionSession
	}
	return nil
}

// StopMeetingRequest 是停止会议参数。
type StopMeetingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 当前用户拥有的会议 UUID。
	MeetingId     string `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopMeetingRequest) Reset() {
	*x = StopMeetingRequest{}
	mi := &file_meeting_v1_meeting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopMeetingRequest) ProtoMessage() {}

func (x *StopMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopMeetingRequest.ProtoReflect.Descriptor instead.
func (*StopMeetingRequest) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{2}
}

func (x *StopMeetingRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

// StopMeetingResponse 返回停止后的最新会议状态。
type StopMeetingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 最新会议状态；响应不承诺已经生成会议纪要。
	Meeting       *Meeting `protobuf:"bytes,1,opt,name=meeting,proto3" json:"meeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopMeetingResponse) Reset() {
	*x = StopMeetingResponse{}
	mi := &file_meeting_v1_meeting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopMeetingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopMeetingResponse) ProtoMessage() {}

func (x *StopMeetingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopMeetingResponse.ProtoReflect.Descriptor instead.
func (*StopMeetingResponse) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{3}
}

func (x *StopMeetingResponse) GetMeeting() *Meeting {
	if x != nil {
		return x.Meeting
	}
	return nil
}

// GetMeetingRequest 是查询会议参数。
type GetMeetingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 当前用户拥有的会议 UUID。
	MeetingId     string `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeetingRequest) Reset() {
	*x = GetMeetingRequest{}
	mi := &file_meeting_v1_meeting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingRequest) ProtoMessage() {}

func (x *GetMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingRequest.ProtoReflect.Descriptor instead.
func (*GetMeetingRequest) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{4}
}

func (x *GetMeetingRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

// GetMeetingResponse 返回会议详情。
type GetMeetingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 当前会议。
	Meeting       *Meeting `protobuf:"bytes,1,opt,name=meeting,proto3" json:"meeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeetingResponse) Reset() {
	*x = GetMeetingResponse{}
	mi := &file_meeting_v1_meeting_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingResponse) ProtoMessage() {}

func (x *GetMeetingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingResponse.ProtoReflect.Descriptor instead.
func (*GetMeetingResponse) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{5}
}

func (x *GetMeetingResponse) GetMeeting() *Meeting {
	if x != nil {
		return x.Meeting
	}
	return nil
}

// ListTranscriptSegmentsRequest 是最终转写片段分页参数。
type ListTranscriptSegmentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 当前用户拥有的会议 UUID。
	MeetingId string `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	// 单页条数；服务端必须限制最大值。
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// 上一页返回的不透明分页令牌。
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTranscriptSegmentsRequest) Reset() {
	*x = ListTranscriptSegmentsRequest{}
	mi := &file_meeting_v1_meeting_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTranscriptSegmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTranscriptSegmentsRequest) ProtoMessage() {}

func (x *ListTranscriptSegmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTranscriptSegmentsRequest.ProtoReflect.Descriptor instead.
func (*ListTranscriptSegmentsRequest) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{6}
}

func (x *ListTranscriptSegmentsRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *ListTranscriptSegmentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTranscriptSegmentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListTranscriptSegmentsResponse 返回一页最终转写片段。
type ListTranscriptSegmentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 按 sequence_no 升序排列的最终片段。
	Segments []*TranscriptSegment `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	// 下一页令牌；为空表示没有下一页。
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTranscriptSegmentsResponse) Reset() {
	*x = ListTranscriptSegmentsResponse{}
	mi := &file_meeting_v1_meeting_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTranscriptSegmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTranscriptSegmentsResponse) ProtoMessage() {}

func (x *ListTranscriptSegmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTranscriptSegmentsResponse.ProtoReflect.Descriptor instead.
func (*ListTranscriptSegmentsResponse) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{7}
}

func (x *ListTranscriptSegmentsResponse) GetSegments() []*TranscriptSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *ListTranscriptSegmentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// GetMeetingSummaryRequest 是查询最新会议纪要的参数。
type GetMeetingSummaryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 当前用户拥有的会议 UUID。
	MeetingId     string `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeetingSummaryRequest) Reset() {
	*x = GetMeetingSummaryRequest{}
	mi := &file_meeting_v1_meeting_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetingSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingSummaryRequest) ProtoMessage() {}

func (x *GetMeetingSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetMeetingSummaryRequest) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{8}
}

func (x *GetMeetingSummaryRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

// GetMeetingSummaryResponse 返回纪要状态和最新成功或正在生成的版本。
type GetMeetingSummaryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 当前纪要生成状态。
	Status MeetingSummaryStatus `protobuf:"varint,1,opt,name=status,proto3,enum=meeting.v1.MeetingSummaryStatus" json:"status,omitempty"`
	// 最新纪要；尚未成功生成时为空。
	Summary *MeetingSummary `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	// 可安全展示的稳定失败原因；非失败状态时为空。
	FailureReason string `protobuf:"bytes,3,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeetingSummaryResponse) Reset() {
	*x = GetMeetingSummaryResponse{}
	mi := &file_meeting_v1_meeting_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetingSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingSummaryResponse) ProtoMessage() {}

func (x *GetMeetingSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetMeetingSummaryResponse) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{9}
}

func (x *GetMeetingSummaryResponse) GetStatus() MeetingSummaryStatus {
	if x != nil {
		return x.Status
	}
	return MeetingSummaryStatus_MEETING_SUMMARY_STATUS_UNSPECIFIED
}

func (x *GetMeetingSummaryResponse) GetSummary() *MeetingSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *GetMeetingSummaryResponse) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

// RegenerateMeetingSummaryRequest 是重新生成会议纪要的参数。
type RegenerateMeetingSummaryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 当前用户拥有的会议 UUID。
	MeetingId     string `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateMeetingSummaryRequest) Reset() {
	*x = RegenerateMeetingSummaryRequest{}
	mi := &file_meeting_v1_meeting_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateMeetingSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateMeetingSummaryRequest) ProtoMessage() {}

func (x *RegenerateMeetingSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateMeetingSummaryRequest.ProtoReflect.Descriptor instead.
func (*RegenerateMeetingSummaryRequest) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{10}
}

func (x *RegenerateMeetingSummaryRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

// RegenerateMeetingSummaryResponse 返回新创建或由幂等键命中的纪要任务。
type RegenerateMeetingSummaryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 新任务的当前生成状态。
	Status MeetingSummaryStatus `protobuf:"varint,1,opt,name=status,proto3,enum=meeting.v1.MeetingSummaryStatus" json:"status,omitempty"`
	// 本次重新生成对应的纪要版本。
	Version       int64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateMeetingSummaryResponse) Reset() {
	*x = RegenerateMeetingSummaryResponse{}
	mi := &file_meeting_v1_meeting_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateMeetingSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateMeetingSummaryResponse) ProtoMessage() {}

func (x *RegenerateMeetingSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateMeetingSummaryResponse.ProtoReflect.Descriptor instead.
func (*RegenerateMeetingSummaryResponse) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{11}
}

func (x *RegenerateMeetingSummaryResponse) GetStatus() MeetingSummaryStatus {
	if x != nil {
		return x.Status
	}
	return MeetingSummaryStatus_MEETING_SUMMARY_STATUS_UNSPECIFIED
}

func (x *RegenerateMeetingSummaryResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// GetMeetingQuotaRequest 查询当前认证用户的额度，无请求字段。
type GetMeetingQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeetingQuotaRequest) Reset() {
	*x = GetMeetingQuotaRequest{}
	mi := &file_meeting_v1_meeting_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetingQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingQuotaRequest) ProtoMessage() {}

func (x *GetMeetingQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingQuotaRequest.ProtoReflect.Descriptor instead.
func (*GetMeetingQuotaRequest) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{12}
}

// GetMeetingQuotaResponse 返回当前用户额度。
type GetMeetingQuotaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 当前计费周期的额度快照。
	Quota         *MeetingQuota `protobuf:"bytes,1,opt,name=quota,proto3" json:"quota,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeetingQuotaResponse) Reset() {
	*x = GetMeetingQuotaResponse{}
	mi := &file_meeting_v1_meeting_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetingQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingQuotaResponse) ProtoMessage() {}

func (x *GetMeetingQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingQuotaResponse.ProtoReflect.Descriptor instead.
func (*GetMeetingQuotaResponse) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{13}
}

func (x *GetMeetingQuotaResponse) GetQuota() *MeetingQuota {
	if x != nil {
		return x.Quota
	}
	return nil
}

// Meeting 是 core-service 拥有的会议资源。
type Meeting struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 会议 UUID。
	MeetingId string `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	// 当前会议业务状态。
	Status MeetingStatus `protobuf:"varint,2,opt,name=status,proto3,enum=meeting.v1.MeetingStatus" json:"status,omitempty"`
	// 当前实时转写阶段状态。
	TranscriptionStatus TranscriptionStatus `protobuf:"varint,3,opt,name=transcription_status,json=transcriptionStatus,proto3,enum=meeting.v1.TranscriptionStatus" json:"transcription_status,omitempty"`
	// 会议识别语言偏好。
	Language MeetingLanguage `protobuf:"varint,4,opt,name=language,proto3,enum=meeting.v1.MeetingLanguage" json:"language,omitempty"`
	// 是否保留云端原始录音。
	RetainAudio bool `protobuf:"varint,5,opt,name=retain_audio,json=retainAudio,proto3" json:"retain_audio,omitempty"`
	// 本次会议获准发送到 ASR 的最大音频时长。
	GrantedAudioDuration *durationpb.Duration `protobuf:"bytes,6,opt,name=granted_audio_duration,json=grantedAudioDuration,proto3" json:"granted_audio_duration,omitempty"`
	// 已开始会议的时间。
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// 停止录音的时间；尚未停止时为空。
	StoppedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=stopped_at,json=stoppedAt,proto3" json:"stopped_at,omitempty"`
	// 资源创建时间。
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 资源最后更新时间。
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// 当前会议纪要生成状态。
	SummaryStatus MeetingSummaryStatus `protobuf:"varint,11,opt,name=summary_status,json=summaryStatus,proto3,enum=meeting.v1.MeetingSummaryStatus" json:"summary_status,omitempty"`
	// 当前对外展示的成功纪要版本；尚无成功纪要时为零。
	SummaryVersion int64 `protobuf:"varint,12,opt,name=summary_version,json=summaryVersion,proto3" json:"summary_version,omitempty"`
	// 当前最终转写快照版本。
	TranscriptRevision int64 `protobuf:"varint,13,opt,name=transcript_revision,json=transcriptRevision,proto3" json:"transcript_revision,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Meeting) Reset() {
	*x = Meeting{}
	mi := &file_meeting_v1_meeting_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meeting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meeting) ProtoMessage() {}

func (x *Meeting) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meeting.ProtoReflect.Descriptor instead.
func (*Meeting) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{14}
}

func (x *Meeting) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *Meeting) GetStatus() MeetingStatus {
	if x != nil {
		return x.Status
	}
	return MeetingStatus_MEETING_STATUS_UNSPECIFIED
}

func (x *Meeting) GetTranscriptionStatus() TranscriptionStatus {
	if x != nil {
		return x.TranscriptionStatus
	}
	return TranscriptionStatus_TRANSCRIPTION_STATUS_UNSPECIFIED
}

func (x *Meeting) GetLanguage() MeetingLanguage {
	if x != nil {
		return x.Language
	}
	return MeetingLanguage_MEETING_LANGUAGE_UNSPECIFIED
}

func (x *Meeting) GetRetainAudio() bool {
	if x != nil {
		return x.RetainAudio
	}
	return false
}

func (x *Meeting) GetGrantedAudioDuration() *durationpb.Duration {
	if x != nil {
		return x.GrantedAudioDuration
	}
	return nil
}

func (x *Meeting) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Meeting) GetStoppedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StoppedAt
	}
	return nil
}

func (x *Meeting) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Meeting) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Meeting) GetSummaryStatus() MeetingSummaryStatus {
	if x != nil {
		return x.SummaryStatus
	}
	return MeetingSummaryStatus_MEETING_SUMMARY_STATUS_UNSPECIFIED
}

func (x *Meeting) GetSummaryVersion() int64 {
	if x != nil {
		return x.SummaryVersion
	}
	return 0
}

func (x *Meeting) GetTranscriptRevision() int64 {
	if x != nil {
		return x.TranscriptRevision
	}
	return 0
}

// MeetingSummary 是经过服务端校验的版本化结构化会议纪要。
type MeetingSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 会议 UUID。
	MeetingId string `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	// 会议内严格递增的纪要版本。
	Version int64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// 本纪要使用的最终转写快照版本。
	SourceTranscriptRevision int64 `protobuf:"varint,3,opt,name=source_transcript_revision,json=sourceTranscriptRevision,proto3" json:"source_transcript_revision,omitempty"`
	// 简短会议主题。
	Topic string `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	// 会议摘要。
	Abstract string `protobuf:"bytes,5,opt,name=abstract,proto3" json:"abstract,omitempty"`
	// 关键讨论内容。
	KeyDiscussions []string `protobuf:"bytes,6,rep,name=key_discussions,json=keyDiscussions,proto3" json:"key_discussions,omitempty"`
	// 已达成的决定。
	Decisions []string `protobuf:"bytes,7,rep,name=decisions,proto3" json:"decisions,omitempty"`
	// 会议待办事项。
	ActionItems []*MeetingActionItem `protobuf:"bytes,8,rep,name=action_items,json=actionItems,proto3" json:"action_items,omitempty"`
	// 风险和待确认事项。
	Risks []string `protobuf:"bytes,9,rep,name=risks,proto3" json:"risks,omitempty"`
	// 实际生成该版本的模型名称。
	ModelName string `protobuf:"bytes,10,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// 生成该版本的服务端 Prompt 版本。
	PromptVersion string `protobuf:"bytes,11,opt,name=prompt_version,json=promptVersion,proto3" json:"prompt_version,omitempty"`
	// 该纪要生成完成的时间。
	GeneratedAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	// 实际处理该版本的 LLM Provider 标识。
	Provider string `protobuf:"bytes,13,opt,name=provider,proto3" json:"provider,omitempty"`
	// Provider 报告的输入 token 数；不提供时为零。
	InputTokens int64 `protobuf:"varint,14,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	// Provider 报告的输出 token 数；不提供时为零。
	OutputTokens  int64 `protobuf:"varint,15,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeetingSummary) Reset() {
	*x = MeetingSummary{}
	mi := &file_meeting_v1_meeting_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeetingSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeetingSummary) ProtoMessage() {}

func (x *MeetingSummary) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeetingSummary.ProtoReflect.Descriptor instead.
func (*MeetingSummary) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{15}
}

func (x *MeetingSummary) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *MeetingSummary) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MeetingSummary) GetSourceTranscriptRevision() int64 {
	if x != nil {
		return x.SourceTranscriptRevision
	}
	return 0
}

func (x *MeetingSummary) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *MeetingSummary) GetAbstract() string {
	if x != nil {
		return x.Abstract
	}
	return ""
}

func (x *MeetingSummary) GetKeyDiscussions() []string {
	if x != nil {
		return x.KeyDiscussions
	}
	return nil
}

func (x *MeetingSummary) GetDecisions() []string {
	if x != nil {
		return x.Decisions
	}
	return nil
}

func (x *MeetingSummary) GetActionItems() []*MeetingActionItem {
	if x != nil {
		return x.ActionItems
	}
	return nil
}

func (x *MeetingSummary) GetRisks() []string {
	if x != nil {
		return x.Risks
	}
	return nil
}

func (x *MeetingSummary) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *MeetingSummary) GetPromptVersion() string {
	if x != nil {
		return x.PromptVersion
	}
	return ""
}

func (x *MeetingSummary) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *MeetingSummary) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *MeetingSummary) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *MeetingSummary) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

// MeetingActionItem 是会议总结提取出的一个待办事项。
type MeetingActionItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 可空负责人。
	Assignee string `protobuf:"bytes,1,opt,name=assignee,proto3" json:"assignee,omitempty"`
	// 明确、可执行的任务描述。
	Task string `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	// 可空的原文期限；无法可靠解析时不转换为时间戳。
	DueText string `protobuf:"bytes,3,opt,name=due_text,json=dueText,proto3" json:"due_text,omitempty"`
	// 待办事项初始状态。
	Status        MeetingActionItemStatus `protobuf:"varint,4,opt,name=status,proto3,enum=meeting.v1.MeetingActionItemStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeetingActionItem) Reset() {
	*x = MeetingActionItem{}
	mi := &file_meeting_v1_meeting_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeetingActionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeetingActionItem) ProtoMessage() {}

func (x *MeetingActionItem) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeetingActionItem.ProtoReflect.Descriptor instead.
func (*MeetingActionItem) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{16}
}

func (x *MeetingActionItem) GetAssignee() string {
	if x != nil {
		return x.Assignee
	}
	return ""
}

func (x *MeetingActionItem) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *MeetingActionItem) GetDueText() string {
	if x != nil {
		return x.DueText
	}
	return ""
}

func (x *MeetingActionItem) GetStatus() MeetingActionItemStatus {
	if x != nil {
		return x.Status
	}
	return MeetingActionItemStatus_MEETING_ACTION_ITEM_STATUS_UNSPECIFIED
}

// TranscriptionSession 是 uTools 建立实时转写 WebSocket 所需的短期参数。
type TranscriptionSession struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// vision-service 转写会话 UUID。
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// vision-service 的完整 WSS 地址，客户端不得自行拼接域名。
	WebsocketUrl string `protobuf:"bytes,2,opt,name=websocket_url,json=websocketUrl,proto3" json:"websocket_url,omitempty"`
	// 仅能消费一次的短期 ticket；不得写入日志或 URL query。
	SessionTicket string `protobuf:"bytes,3,opt,name=session_ticket,json=sessionTicket,proto3" json:"session_ticket,omitempty"`
	// ticket 到期时间。
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// 本次会话实际接受的实时音频约束。
	Audio *AudioSpec `protobuf:"bytes,5,opt,name=audio,proto3" json:"audio,omitempty"`
	// core-service 为本次 session 预占并授予的最大音频时长。
	GrantedAudioDuration *durationpb.Duration `protobuf:"bytes,6,opt,name=granted_audio_duration,json=grantedAudioDuration,proto3" json:"granted_audio_duration,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TranscriptionSession) Reset() {
	*x = TranscriptionSession{}
	mi := &file_meeting_v1_meeting_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptionSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptionSession) ProtoMessage() {}

func (x *TranscriptionSession) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptionSession.ProtoReflect.Descriptor instead.
func (*TranscriptionSession) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{17}
}

func (x *TranscriptionSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TranscriptionSession) GetWebsocketUrl() string {
	if x != nil {
		return x.WebsocketUrl
	}
	return ""
}

func (x *TranscriptionSession) GetSessionTicket() string {
	if x != nil {
		return x.SessionTicket
	}
	return ""
}

func (x *TranscriptionSession) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *TranscriptionSession) GetAudio() *AudioSpec {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *TranscriptionSession) GetGrantedAudioDuration() *durationpb.Duration {
	if x != nil {
		return x.GrantedAudioDuration
	}
	return nil
}

// AudioSpec 描述实时音频编码和分片边界。
type AudioSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 规范化音频格式。
	Format AudioFormat `protobuf:"varint,1,opt,name=format,proto3,enum=meeting.v1.AudioFormat" json:"format,omitempty"`
	// 供浏览器和 uTools 选择编码器的标准 MIME。
	MimeType string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// 采样率，单位 Hz。
	SampleRate int32 `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	// 声道数；V1 必须为 1。
	Channels int32 `protobuf:"varint,4,opt,name=channels,proto3" json:"channels,omitempty"`
	// 推荐音频分片时长。
	ChunkDuration *durationpb.Duration `protobuf:"bytes,5,opt,name=chunk_duration,json=chunkDuration,proto3" json:"chunk_duration,omitempty"`
	// 单个业务 WebSocket 音频消息允许的最大音频字节数。
	MaxChunkBytes int32 `protobuf:"varint,6,opt,name=max_chunk_bytes,json=maxChunkBytes,proto3" json:"max_chunk_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioSpec) Reset() {
	*x = AudioSpec{}
	mi := &file_meeting_v1_meeting_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioSpec) ProtoMessage() {}

func (x *AudioSpec) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioSpec.ProtoReflect.Descriptor instead.
func (*AudioSpec) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{18}
}

func (x *AudioSpec) GetFormat() AudioFormat {
	if x != nil {
		return x.Format
	}
	return AudioFormat_AUDIO_FORMAT_UNSPECIFIED
}

func (x *AudioSpec) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *AudioSpec) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioSpec) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *AudioSpec) GetChunkDuration() *durationpb.Duration {
	if x != nil {
		return x.ChunkDuration
	}
	return nil
}

func (x *AudioSpec) GetMaxChunkBytes() int32 {
	if x != nil {
		return x.MaxChunkBytes
	}
	return 0
}

// TranscriptSegment 是已经最终确认、可以持久化的转写片段。
type TranscriptSegment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// vision-service 生成的稳定片段 ID。
	SegmentId string `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	// 会议内严格递增的最终片段序号。
	SequenceNo int64 `protobuf:"varint,2,opt,name=sequence_no,json=sequenceNo,proto3" json:"sequence_no,omitempty"`
	// 片段相对会议音频的开始偏移。
	StartOffset *durationpb.Duration `protobuf:"bytes,3,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	// 片段相对会议音频的结束偏移。
	EndOffset *durationpb.Duration `protobuf:"bytes,4,opt,name=end_offset,json=endOffset,proto3" json:"end_offset,omitempty"`
	// 可空的临时说话人标签；V1 不承诺真实身份。
	SpeakerLabel string `protobuf:"bytes,5,opt,name=speaker_label,json=speakerLabel,proto3" json:"speaker_label,omitempty"`
	// 最终转写正文。
	Content string `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	// 该片段识别出的语言。
	Language MeetingLanguage `protobuf:"varint,7,opt,name=language,proto3,enum=meeting.v1.MeetingLanguage" json:"language,omitempty"`
	// Provider 返回的置信度；Provider 不提供时为空。
	Confidence *float32 `protobuf:"fixed32,8,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"`
	// 最终片段生成时间。
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptSegment) Reset() {
	*x = TranscriptSegment{}
	mi := &file_meeting_v1_meeting_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptSegment) ProtoMessage() {}

func (x *TranscriptSegment) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptSegment.ProtoReflect.Descriptor instead.
func (*TranscriptSegment) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{19}
}

func (x *TranscriptSegment) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *TranscriptSegment) GetSequenceNo() int64 {
	if x != nil {
		return x.SequenceNo
	}
	return 0
}

func (x *TranscriptSegment) GetStartOffset() *durationpb.Duration {
	if x != nil {
		return x.StartOffset
	}
	return nil
}

func (x *TranscriptSegment) GetEndOffset() *durationpb.Duration {
	if x != nil {
		return x.EndOffset
	}
	return nil
}

func (x *TranscriptSegment) GetSpeakerLabel() string {
	if x != nil {
		return x.SpeakerLabel
	}
	return ""
}

func (x *TranscriptSegment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TranscriptSegment) GetLanguage() MeetingLanguage {
	if x != nil {
		return x.Language
	}
	return MeetingLanguage_MEETING_LANGUAGE_UNSPECIFIED
}

func (x *TranscriptSegment) GetConfidence() float32 {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return 0
}

func (x *TranscriptSegment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// MeetingQuota 是当前用户在一个计费周期内的额度快照。
type MeetingQuota struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 当前自然月周期开始时间。
	PeriodStart *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	// 当前自然月周期结束时间。
	PeriodEnd *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	// 当前周期允许的音频总时长；为兼容旧客户端保留，值与 total_limit 相同。
	Limit *durationpb.Duration `protobuf:"bytes,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// 已最终结算的音频时长。
	Consumed *durationpb.Duration `protobuf:"bytes,4,opt,name=consumed,proto3" json:"consumed,omitempty"`
	// 已由活跃会议预占但尚未结算的音频时长。
	Reserved *durationpb.Duration `protobuf:"bytes,5,opt,name=reserved,proto3" json:"reserved,omitempty"`
	// 当前仍可预占的音频时长。
	Remaining *durationpb.Duration `protobuf:"bytes,6,opt,name=remaining,proto3" json:"remaining,omitempty"`
	// 单场会议硬上限。
	MaxMeetingDuration *durationpb.Duration `protobuf:"bytes,7,opt,name=max_meeting_duration,json=maxMeetingDuration,proto3" json:"max_meeting_duration,omitempty"`
	// 单用户允许的活跃会议数。
	MaxConcurrentMeetings int32 `protobuf:"varint,8,opt,name=max_concurrent_meetings,json=maxConcurrentMeetings,proto3" json:"max_concurrent_meetings,omitempty"`
	// 当前活跃会议数。
	ActiveMeetings int32 `protobuf:"varint,9,opt,name=active_meetings,json=activeMeetings,proto3" json:"active_meetings,omitempty"`
	// 当前周期从默认策略或用户覆盖配置快照得到的基础额度。
	BaseLimit *durationpb.Duration `protobuf:"bytes,10,opt,name=base_limit,json=baseLimit,proto3" json:"base_limit,omitempty"`
	// 当前周期已支付订单累计增加的额度。
	PurchasedLimit *durationpb.Duration `protobuf:"bytes,11,opt,name=purchased_limit,json=purchasedLimit,proto3" json:"purchased_limit,omitempty"`
	// 当前周期基础额度与购买额度之和。
	TotalLimit    *durationpb.Duration `protobuf:"bytes,12,opt,name=total_limit,json=totalLimit,proto3" json:"total_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeetingQuota) Reset() {
	*x = MeetingQuota{}
	mi := &file_meeting_v1_meeting_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeetingQuota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeetingQuota) ProtoMessage() {}

func (x *MeetingQuota) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeetingQuota.ProtoReflect.Descriptor instead.
func (*MeetingQuota) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_proto_rawDescGZIP(), []int{20}
}

func (x *MeetingQuota) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *MeetingQuota) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

func (x *MeetingQuota) GetLimit() *durationpb.Duration {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *MeetingQuota) GetConsumed() *durationpb.Duration {
	if x != nil {
		return x.Consumed
	}
	return nil
}

func (x *MeetingQuota) GetReserved() *durationpb.Duration {
	if x != nil {
		return x.Reserved
	}
	return nil
}

func (x *MeetingQuota) GetRemaining() *durationpb.Duration {
	if x != nil {
		return x.Remaining
	}
	return nil
}

func (x *MeetingQuota) GetMaxMeetingDuration() *durationpb.Duration {
	if x != nil {
		return x.MaxMeetingDuration
	}
	return nil
}

func (x *MeetingQuota) GetMaxConcurrentMeetings() int32 {
	if x != nil {
		return x.MaxConcurrentMeetings
	}
	return 0
}

func (x *MeetingQuota) GetActiveMeetings() int32 {
	if x != nil {
		return x.ActiveMeetings
	}
	return 0
}

func (x *MeetingQuota) GetBaseLimit() *durationpb.Duration {
	if x != nil {
		return x.BaseLimit
	}
	return nil
}

func (x *MeetingQuota) GetPurchasedLimit() *durationpb.Duration {
	if x != nil {
		return x.PurchasedLimit
	}
	return nil
}

func (x *MeetingQuota) GetTotalLimit() *durationpb.Duration {
	if x != nil {
		return x.TotalLimit
	}
	return nil
}

var File_meeting_v1_meeting_proto protoreflect.FileDescriptor

const file_meeting_v1_meeting_proto_rawDesc = "" +
	"\n" +
	"\x18meeting/v1/meeting.proto\x12\n" +
	"meeting.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb1\x01\n" +
	"\x14CreateMeetingRequest\x12<\n" +
	"\blanguage\x18\x01 \x01(\x0e2\x1b.meeting.v1.MeetingLanguageB\x03\xe0A\x02R\blanguage\x12!\n" +
	"\fretain_audio\x18\x02 \x01(\bR\vretainAudio\x128\n" +
	"\x15transcription_consent\x18\x03 \x01(\bB\x03\xe0A\x02R\x14transcriptionConsent\"\x9d\x01\n" +
	"\x15CreateMeetingResponse\x12-\n" +
	"\ameeting\x18\x01 \x01(\v2\x13.meeting.v1.MeetingR\ameeting\x12U\n" +
	"\x15transcription_session\x18\x02 \x01(\v2 .meeting.v1.TranscriptionSessionR\x14transcriptionSession\"8\n" +
	"\x12StopMeetingRequest\x12\"\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tmeetingId\"D\n" +
	"\x13StopMeetingResponse\x12-\n" +
	"\ameeting\x18\x01 \x01(\v2\x13.meeting.v1.MeetingR\ameeting\"7\n" +
	"\x11GetMeetingRequest\x12\"\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tmeetingId\"C\n" +
	"\x12GetMeetingResponse\x12-\n" +
	"\ameeting\x18\x01 \x01(\v2\x13.meeting.v1.MeetingR\ameeting\"\x7f\n" +
	"\x1dListTranscriptSegmentsRequest\x12\"\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tmeetingId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x83\x01\n" +
	"\x1eListTranscriptSegmentsResponse\x129\n" +
	"\bsegments\x18\x01 \x03(\v2\x1d.meeting.v1.TranscriptSegmentR\bsegments\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\">\n" +
	"\x18GetMeetingSummaryRequest\x12\"\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tmeetingId\"\xb2\x01\n" +
	"\x19GetMeetingSummaryResponse\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2 .meeting.v1.MeetingSummaryStatusR\x06status\x124\n" +
	"\asummary\x18\x02 \x01(\v2\x1a.meeting.v1.MeetingSummaryR\asummary\x12%\n" +
	"\x0efailure_reason\x18\x03 \x01(\tR\rfailureReason\"E\n" +
	"\x1fRegenerateMeetingSummaryRequest\x12\"\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tmeetingId\"v\n" +
	" RegenerateMeetingSummaryResponse\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2 .meeting.v1.MeetingSummaryStatusR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\"\x18\n" +
	"\x16GetMeetingQuotaRequest\"I\n" +
	"\x17GetMeetingQuotaResponse\x12.\n" +
	"\x05quota\x18\x01 \x01(\v2\x18.meeting.v1.MeetingQuotaR\x05quota\"\xeb\x05\n" +
	"\aMeeting\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.meeting.v1.MeetingStatusR\x06status\x12R\n" +
	"\x14transcription_status\x18\x03 \x01(\x0e2\x1f.meeting.v1.TranscriptionStatusR\x13transcriptionStatus\x127\n" +
	"\blanguage\x18\x04 \x01(\x0e2\x1b.meeting.v1.MeetingLanguageR\blanguage\x12!\n" +
	"\fretain_audio\x18\x05 \x01(\bR\vretainAudio\x12O\n" +
	"\x16granted_audio_duration\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x14grantedAudioDuration\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x129\n" +
	"\n" +
	"stopped_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstoppedAt\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12G\n" +
	"\x0esummary_status\x18\v \x01(\x0e2 .meeting.v1.MeetingSummaryStatusR\rsummaryStatus\x12'\n" +
	"\x0fsummary_version\x18\f \x01(\x03R\x0esummaryVersion\x12/\n" +
	"\x13transcript_revision\x18\r \x01(\x03R\x12transcriptRevision\"\xc1\x04\n" +
	"\x0eMeetingSummary\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12<\n" +
	"\x1asource_transcript_revision\x18\x03 \x01(\x03R\x18sourceTranscriptRevision\x12\x14\n" +
	"\x05topic\x18\x04 \x01(\tR\x05topic\x12\x1a\n" +
	"\babstract\x18\x05 \x01(\tR\babstract\x12'\n" +
	"\x0fkey_discussions\x18\x06 \x03(\tR\x0ekeyDiscussions\x12\x1c\n" +
	"\tdecisions\x18\a \x03(\tR\tdecisions\x12@\n" +
	"\faction_items\x18\b \x03(\v2\x1d.meeting.v1.MeetingActionItemR\vactionItems\x12\x14\n" +
	"\x05risks\x18\t \x03(\tR\x05risks\x12\x1d\n" +
	"\n" +
	"model_name\x18\n" +
	" \x01(\tR\tmodelName\x12%\n" +
	"\x0eprompt_version\x18\v \x01(\tR\rpromptVersion\x12=\n" +
	"\fgenerated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x12\x1a\n" +
	"\bprovider\x18\r \x01(\tR\bprovider\x12!\n" +
	"\finput_tokens\x18\x0e \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x0f \x01(\x03R\foutputTokens\"\x9b\x01\n" +
	"\x11MeetingActionItem\x12\x1a\n" +
	"\bassignee\x18\x01 \x01(\tR\bassignee\x12\x12\n" +
	"\x04task\x18\x02 \x01(\tR\x04task\x12\x19\n" +
	"\bdue_text\x18\x03 \x01(\tR\adueText\x12;\n" +
	"\x06status\x18\x04 \x01(\x0e2#.meeting.v1.MeetingActionItemStatusR\x06status\"\xba\x02\n" +
	"\x14TranscriptionSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rwebsocket_url\x18\x02 \x01(\tR\fwebsocketUrl\x12%\n" +
	"\x0esession_ticket\x18\x03 \x01(\tR\rsessionTicket\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12+\n" +
	"\x05audio\x18\x05 \x01(\v2\x15.meeting.v1.AudioSpecR\x05audio\x12O\n" +
	"\x16granted_audio_duration\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x14grantedAudioDuration\"\x80\x02\n" +
	"\tAudioSpec\x12/\n" +
	"\x06format\x18\x01 \x01(\x0e2\x17.meeting.v1.AudioFormatR\x06format\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x1f\n" +
	"\vsample_rate\x18\x03 \x01(\x05R\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\x04 \x01(\x05R\bchannels\x12@\n" +
	"\x0echunk_duration\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\rchunkDuration\x12&\n" +
	"\x0fmax_chunk_bytes\x18\x06 \x01(\x05R\rmaxChunkBytes\"\xb2\x03\n" +
	"\x11TranscriptSegment\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\tR\tsegmentId\x12\x1f\n" +
	"\vsequence_no\x18\x02 \x01(\x03R\n" +
	"sequenceNo\x12<\n" +
	"\fstart_offset\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vstartOffset\x128\n" +
	"\n" +
	"end_offset\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\tendOffset\x12#\n" +
	"\rspeaker_label\x18\x05 \x01(\tR\fspeakerLabel\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x127\n" +
	"\blanguage\x18\a \x01(\x0e2\x1b.meeting.v1.MeetingLanguageR\blanguage\x12#\n" +
	"\n" +
	"confidence\x18\b \x01(\x02H\x00R\n" +
	"confidence\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\r\n" +
	"\v_confidence\"\xc8\x05\n" +
	"\fMeetingQuota\x12=\n" +
	"\fperiod_start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\x12/\n" +
	"\x05limit\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x05limit\x125\n" +
	"\bconsumed\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bconsumed\x125\n" +
	"\breserved\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\breserved\x127\n" +
	"\tremaining\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\tremaining\x12K\n" +
	"\x14max_meeting_duration\x18\a \x01(\v2\x19.google.protobuf.DurationR\x12maxMeetingDuration\x126\n" +
	"\x17max_concurrent_meetings\x18\b \x01(\x05R\x15maxConcurrentMeetings\x12'\n" +
	"\x0factive_meetings\x18\t \x01(\x05R\x0eactiveMeetings\x128\n" +
	"\n" +
	"base_limit\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\tbaseLimit\x12B\n" +
	"\x0fpurchased_limit\x18\v \x01(\v2\x19.google.protobuf.DurationR\x0epurchasedLimit\x12:\n" +
	"\vtotal_limit\x18\f \x01(\v2\x19.google.protobuf.DurationR\n" +
	"totalLimit*\xeb\x01\n" +
	"\rMeetingStatus\x12\x1e\n" +
	"\x1aMEETING_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18MEETING_STATUS_RECORDING\x10\x01\x12\x1d\n" +
	"\x19MEETING_STATUS_PROCESSING\x10\x02\x12\x1c\n" +
	"\x18MEETING_STATUS_COMPLETED\x10\x03\x12&\n" +
	"\"MEETING_STATUS_PARTIALLY_COMPLETED\x10\x04\x12\x19\n" +
	"\x15MEETING_STATUS_FAILED\x10\x05\x12\x1c\n" +
	"\x18MEETING_STATUS_CANCELLED\x10\x06*\xd5\x02\n" +
	"\x13TranscriptionStatus\x12$\n" +
	" TRANSCRIPTION_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cTRANSCRIPTION_STATUS_PENDING\x10\x01\x12#\n" +
	"\x1fTRANSCRIPTION_STATUS_CONNECTING\x10\x02\x12\"\n" +
	"\x1eTRANSCRIPTION_STATUS_STREAMING\x10\x03\x12\"\n" +
	"\x1eTRANSCRIPTION_STATUS_FINISHING\x10\x04\x12\"\n" +
	"\x1eTRANSCRIPTION_STATUS_SUCCEEDED\x10\x05\x12\x1f\n" +
	"\x1bTRANSCRIPTION_STATUS_FAILED\x10\x06\x12\"\n" +
	"\x1eTRANSCRIPTION_STATUS_CANCELLED\x10\a\x12 \n" +
	"\x1cTRANSCRIPTION_STATUS_EXPIRED\x10\b*\xfa\x01\n" +
	"\x14MeetingSummaryStatus\x12&\n" +
	"\"MEETING_SUMMARY_STATUS_UNSPECIFIED\x10\x00\x12&\n" +
	"\"MEETING_SUMMARY_STATUS_NOT_STARTED\x10\x01\x12\"\n" +
	"\x1eMEETING_SUMMARY_STATUS_PENDING\x10\x02\x12%\n" +
	"!MEETING_SUMMARY_STATUS_PROCESSING\x10\x03\x12$\n" +
	" MEETING_SUMMARY_STATUS_SUCCEEDED\x10\x04\x12!\n" +
	"\x1dMEETING_SUMMARY_STATUS_FAILED\x10\x05*m\n" +
	"\x17MeetingActionItemStatus\x12*\n" +
	"&MEETING_ACTION_ITEM_STATUS_UNSPECIFIED\x10\x00\x12&\n" +
	"\"MEETING_ACTION_ITEM_STATUS_PENDING\x10\x01*\x86\x01\n" +
	"\x0fMeetingLanguage\x12 \n" +
	"\x1cMEETING_LANGUAGE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15MEETING_LANGUAGE_AUTO\x10\x01\x12\x1a\n" +
	"\x16MEETING_LANGUAGE_ZH_CN\x10\x02\x12\x1a\n" +
	"\x16MEETING_LANGUAGE_EN_US\x10\x03*G\n" +
	"\vAudioFormat\x12\x1c\n" +
	"\x18AUDIO_FORMAT_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16AUDIO_FORMAT_PCM_S16LE\x10\x012\xc9\a\n" +
	"\x0eMeetingService\x12m\n" +
	"\rCreateMeeting\x12 .meeting.v1.CreateMeetingRequest\x1a!.meeting.v1.CreateMeetingResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/meetings\x12y\n" +
	"\vStopMeeting\x12\x1e.meeting.v1.StopMeetingRequest\x1a\x1f.meeting.v1.StopMeetingResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/meetings/{meeting_id}:stop\x12n\n" +
	"\n" +
	"GetMeeting\x12\x1d.meeting.v1.GetMeetingRequest\x1a\x1e.meeting.v1.GetMeetingResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/meetings/{meeting_id}\x12\xa6\x01\n" +
	"\x16ListTranscriptSegments\x12).meeting.v1.ListTranscriptSegmentsRequest\x1a*.meeting.v1.ListTranscriptSegmentsResponse\"5\x82\xd3\xe4\x93\x02/\x12-/v1/meetings/{meeting_id}/transcript-segments\x12\x8b\x01\n" +
	"\x11GetMeetingSummary\x12$.meeting.v1.GetMeetingSummaryRequest\x1a%.meeting.v1.GetMeetingSummaryResponse\")\x82\xd3\xe4\x93\x02#\x12!/v1/meetings/{meeting_id}/summary\x12\xae\x01\n" +
	"\x18RegenerateMeetingSummary\x12+.meeting.v1.RegenerateMeetingSummaryRequest\x1a,.meeting.v1.RegenerateMeetingSummaryResponse\"7\x82\xd3\xe4\x93\x021:\x01*\",/v1/meetings/{meeting_id}/summary:regenerate\x12u\n" +
	"\x0fGetMeetingQuota\x12\".meeting.v1.GetMeetingQuotaRequest\x1a#.meeting.v1.GetMeetingQuotaResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/meeting-quotaB<Z:github.com/tiehu-ai/tiehu-fitness/api/meeting/v1;meetingv1b\x06proto3"

var (
	file_meeting_v1_meeting_proto_rawDescOnce sync.Once
	file_meeting_v1_meeting_proto_rawDescData []byte
)

func file_meeting_v1_meeting_proto_rawDescGZIP() []byte {
	file_meeting_v1_meeting_proto_rawDescOnce.Do(func() {
		file_meeting_v1_meeting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meeting_v1_meeting_proto_rawDesc), len(file_meeting_v1_meeting_proto_rawDesc)))
	})
	return file_meeting_v1_meeting_proto_rawDescData
}

var file_meeting_v1_meeting_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_meeting_v1_meeting_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_meeting_v1_meeting_proto_goTypes = []any{
	(MeetingStatus)(0),                       // 0: meeting.v1.MeetingStatus
	(TranscriptionStatus)(0),                 // 1: meeting.v1.TranscriptionStatus
	(MeetingSummaryStatus)(0),                // 2: meeting.v1.MeetingSummaryStatus
	(MeetingActionItemStatus)(0),             // 3: meeting.v1.MeetingActionItemStatus
	(MeetingLanguage)(0),                     // 4: meeting.v1.MeetingLanguage
	(AudioFormat)(0),                         // 5: meeting.v1.AudioFormat
	(*CreateMeetingRequest)(nil),             // 6: meeting.v1.CreateMeetingRequest
	(*CreateMeetingResponse)(nil),            // 7: meeting.v1.CreateMeetingResponse
	(*StopMeetingRequest)(nil),               // 8: meeting.v1.StopMeetingRequest
	(*StopMeetingResponse)(nil),              // 9: meeting.v1.StopMeetingResponse
	(*GetMeetingRequest)(nil),                // 10: meeting.v1.GetMeetingRequest
	(*GetMeetingResponse)(nil),               // 11: meeting.v1.GetMeetingResponse
	(*ListTranscriptSegmentsRequest)(nil),    // 12: meeting.v1.ListTranscriptSegmentsRequest
	(*ListTranscriptSegmentsResponse)(nil),   // 13: meeting.v1.ListTranscriptSegmentsResponse
	(*GetMeetingSummaryRequest)(nil),         // 14: meeting.v1.GetMeetingSummaryRequest
	(*GetMeetingSummaryResponse)(nil),        // 15: meeting.v1.GetMeetingSummaryResponse
	(*RegenerateMeetingSummaryRequest)(nil),  // 16: meeting.v1.RegenerateMeetingSummaryRequest
	(*RegenerateMeetingSummaryResponse)(nil), // 17: meeting.v1.RegenerateMeetingSummaryResponse
	(*GetMeetingQuotaRequest)(nil),           // 18: meeting.v1.GetMeetingQuotaRequest
	(*GetMeetingQuotaResponse)(nil),          // 19: meeting.v1.GetMeetingQuotaResponse
	(*Meeting)(nil),                          // 20: meeting.v1.Meeting
	(*MeetingSummary)(nil),                   // 21: meeting.v1.MeetingSummary
	(*MeetingActionItem)(nil),                // 22: meeting.v1.MeetingActionItem
	(*TranscriptionSession)(nil),             // 23: meeting.v1.TranscriptionSession
	(*AudioSpec)(nil),                        // 24: meeting.v1.AudioSpec
	(*TranscriptSegment)(nil),                // 25: meeting.v1.TranscriptSegment
	(*MeetingQuota)(nil),                     // 26: meeting.v1.MeetingQuota
	(*durationpb.Duration)(nil),              // 27: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),            // 28: google.protobuf.Timestamp
}
var file_meeting_v1_meeting_proto_depIdxs = []int32{
	4,  // 0: meeting.v1.CreateMeetingRequest.language:type_name -> meeting.v1.MeetingLanguage
	20, // 1: meeting.v1.CreateMeetingResponse.meeting:type_name -> meeting.v1.Meeting
	23, // 2: meeting.v1.CreateMeetingResponse.transcription_session:type_name -> meeting.v1.TranscriptionSession
	20, // 3: meeting.v1.StopMeetingResponse.meeting:type_name -> meeting.v1.Meeting
	20, // 4: meeting.v1.GetMeetingResponse.meeting:type_name -> meeting.v1.Meeting
	25, // 5: meeting.v1.ListTranscriptSegmentsResponse.segments:type_name -> meeting.v1.TranscriptSegment
	2,  // 6: meeting.v1.GetMeetingSummaryResponse.status:type_name -> meeting.v1.MeetingSummaryStatus
	21, // 7: meeting.v1.GetMeetingSummaryResponse.summary:type_name -> meeting.v1.MeetingSummary
	2,  // 8: meeting.v1.RegenerateMeetingSummaryResponse.status:type_name -> meeting.v1.MeetingSummaryStatus
	26, // 9: meeting.v1.GetMeetingQuotaResponse.quota:type_name -> meeting.v1.MeetingQuota
	0,  // 10: meeting.v1.Meeting.status:type_name -> meeting.v1.MeetingStatus
	1,  // 11: meeting.v1.Meeting.transcription_status:type_name -> meeting.v1.TranscriptionStatus
	4,  // 12: meeting.v1.Meeting.language:type_name -> meeting.v1.MeetingLanguage
	27, // 13: meeting.v1.Meeting.granted_audio_duration:type_name -> google.protobuf.Duration
	28, // 14: meeting.v1.Meeting.started_at:type_name -> google.protobuf.Timestamp
	28, // 15: meeting.v1.Meeting.stopped_at:type_name -> google.protobuf.Timestamp
	28, // 16: meeting.v1.Meeting.created_at:type_name -> google.protobuf.Timestamp
	28, // 17: meeting.v1.Meeting.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 18: meeting.v1.Meeting.summary_status:type_name -> meeting.v1.MeetingSummaryStatus
	22, // 19: meeting.v1.MeetingSummary.action_items:type_name -> meeting.v1.MeetingActionItem
	28, // 20: meeting.v1.MeetingSummary.generated_at:type_name -> google.protobuf.Timestamp
	3,  // 21: meeting.v1.MeetingActionItem.status:type_name -> meeting.v1.MeetingActionItemStatus
	28, // 22: meeting.v1.TranscriptionSession.expires_at:type_name -> google.protobuf.Timestamp
	24, // 23: meeting.v1.TranscriptionSession.audio:type_name -> meeting.v1.AudioSpec
	27, // 24: meeting.v1.TranscriptionSession.granted_audio_duration:type_name -> google.protobuf.Duration
	5,  // 25: meeting.v1.AudioSpec.format:type_name -> meeting.v1.AudioFormat
	27, // 26: meeting.v1.AudioSpec.chunk_duration:type_name -> google.protobuf.Duration
	27, // 27: meeting.v1.TranscriptSegment.start_offset:type_name -> google.protobuf.Duration
	27, // 28: meeting.v1.TranscriptSegment.end_offset:type_name -> google.protobuf.Duration
	4,  // 29: meeting.v1.TranscriptSegment.language:type_name -> meeting.v1.MeetingLanguage
	28, // 30: meeting.v1.TranscriptSegment.created_at:type_name -> google.protobuf.Timestamp
	28, // 31: meeting.v1.MeetingQuota.period_start:type_name -> google.protobuf.Timestamp
	28, // 32: meeting.v1.MeetingQuota.period_end:type_name -> google.protobuf.Timestamp
	27, // 33: meeting.v1.MeetingQuota.limit:type_name -> google.protobuf.Duration
	27, // 34: meeting.v1.MeetingQuota.consumed:type_name -> google.protobuf.Duration
	27, // 35: meeting.v1.MeetingQuota.reserved:type_name -> google.protobuf.Duration
	27, // 36: meeting.v1.MeetingQuota.remaining:type_name -> google.protobuf.Duration
	27, // 37: meeting.v1.MeetingQuota.max_meeting_duration:type_name -> google.protobuf.Duration
	27, // 38: meeting.v1.MeetingQuota.base_limit:type_name -> google.protobuf.Duration
	27, // 39: meeting.v1.MeetingQuota.purchased_limit:type_name -> google.protobuf.Duration
	27, // 40: meeting.v1.MeetingQuota.total_limit:type_name -> google.protobuf.Duration
	6,  // 41: meeting.v1.MeetingService.CreateMeeting:input_type -> meeting.v1.CreateMeetingRequest
	8,  // 42: meeting.v1.MeetingService.StopMeeting:input_type -> meeting.v1.StopMeetingRequest
	10, // 43: meeting.v1.MeetingService.GetMeeting:input_type -> meeting.v1.GetMeetingRequest
	12, // 44: meeting.v1.MeetingService.ListTranscriptSegments:input_type -> meeting.v1.ListTranscriptSegmentsRequest
	14, // 45: meeting.v1.MeetingService.GetMeetingSummary:input_type -> meeting.v1.GetMeetingSummaryRequest
	16, // 46: meeting.v1.MeetingService.RegenerateMeetingSummary:input_type -> meeting.v1.RegenerateMeetingSummaryRequest
	18, // 47: meeting.v1.MeetingService.GetMeetingQuota:input_type -> meeting.v1.GetMeetingQuotaRequest
	7,  // 48: meeting.v1.MeetingService.CreateMeeting:output_type -> meeting.v1.CreateMeetingResponse
	9,  // 49: meeting.v1.MeetingService.StopMeeting:output_type -> meeting.v1.StopMeetingResponse
	11, // 50: meeting.v1.MeetingService.GetMeeting:output_type -> meeting.v1.GetMeetingResponse
	13, // 51: meeting.v1.MeetingService.ListTranscriptSegments:output_type -> meeting.v1.ListTranscriptSegmentsResponse
	15, // 52: meeting.v1.MeetingService.GetMeetingSummary:output_type -> meeting.v1.GetMeetingSummaryResponse
	17, // 53: meeting.v1.MeetingService.RegenerateMeetingSummary:output_type -> meeting.v1.RegenerateMeetingSummaryResponse
	19, // 54: meeting.v1.MeetingService.GetMeetingQuota:output_type -> meeting.v1.GetMeetingQuotaResponse
	48, // [48:55] is the sub-list for method output_type
	41, // [41:48] is the sub-list for method input_type
	41, // [41:41] is the sub-list for extension type_name
	41, // [41:41] is the sub-list for extension extendee
	0,  // [0:41] is the sub-list for field type_name
}

func init() { file_meeting_v1_meeting_proto_init() }
func file_meeting_v1_meeting_proto_init() {
	if File_meeting_v1_meeting_proto != nil {
		return
	}
	file_meeting_v1_meeting_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meeting_v1_meeting_proto_rawDesc), len(file_meeting_v1_meeting_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meeting_v1_meeting_proto_goTypes,
		DependencyIndexes: file_meeting_v1_meeting_proto_depIdxs,
		EnumInfos:         file_meeting_v1_meeting_proto_enumTypes,
		MessageInfos:      file_meeting_v1_meeting_proto_msgTypes,
	}.Build()
	File_meeting_v1_meeting_proto = out.File
	file_meeting_v1_meeting_proto_goTypes = nil
	file_meeting_v1_meeting_proto_depIdxs = nil
}
