// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: meeting/v1/meeting.proto

package meetingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MeetingService_CreateMeeting_FullMethodName            = "/meeting.v1.MeetingService/CreateMeeting"
	MeetingService_StopMeeting_FullMethodName              = "/meeting.v1.MeetingService/StopMeeting"
	MeetingService_GetMeeting_FullMethodName               = "/meeting.v1.MeetingService/GetMeeting"
	MeetingService_ListTranscriptSegments_FullMethodName   = "/meeting.v1.MeetingService/ListTranscriptSegments"
	MeetingService_GetMeetingSummary_FullMethodName        = "/meeting.v1.MeetingService/GetMeetingSummary"
	MeetingService_RegenerateMeetingSummary_FullMethodName = "/meeting.v1.MeetingService/RegenerateMeetingSummary"
	MeetingService_GetMeetingQuota_FullMethodName          = "/meeting.v1.MeetingService/GetMeetingQuota"
)

// MeetingServiceClient is the client API for MeetingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MeetingService 提供当前登录用户的会议控制、额度和最终转写查询能力。
type MeetingServiceClient interface {
	// CreateMeeting 创建并开始会议；HTTP 调用必须携带 Idempotency-Key。
	CreateMeeting(ctx context.Context, in *CreateMeetingRequest, opts ...grpc.CallOption) (*CreateMeetingResponse, error)
	// StopMeeting 幂等停止会议；HTTP 调用必须携带 Idempotency-Key。
	StopMeeting(ctx context.Context, in *StopMeetingRequest, opts ...grpc.CallOption) (*StopMeetingResponse, error)
	// GetMeeting 查询当前用户拥有的会议及转写阶段状态。
	GetMeeting(ctx context.Context, in *GetMeetingRequest, opts ...grpc.CallOption) (*GetMeetingResponse, error)
	// ListTranscriptSegments 分页查询会议的最终转写片段。
	ListTranscriptSegments(ctx context.Context, in *ListTranscriptSegmentsRequest, opts ...grpc.CallOption) (*ListTranscriptSegmentsResponse, error)
	// GetMeetingSummary 查询当前会议最新可展示的结构化纪要及生成状态。
	GetMeetingSummary(ctx context.Context, in *GetMeetingSummaryRequest, opts ...grpc.CallOption) (*GetMeetingSummaryResponse, error)
	// RegenerateMeetingSummary 基于当前最终转写版本异步重新生成纪要；HTTP 调用必须携带 Idempotency-Key。
	RegenerateMeetingSummary(ctx context.Context, in *RegenerateMeetingSummaryRequest, opts ...grpc.CallOption) (*RegenerateMeetingSummaryResponse, error)
	// GetMeetingQuota 查询当前用户在本计费周期的会议额度。
	GetMeetingQuota(ctx context.Context, in *GetMeetingQuotaRequest, opts ...grpc.CallOption) (*GetMeetingQuotaResponse, error)
}

type meetingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeetingServiceClient(cc grpc.ClientConnInterface) MeetingServiceClient {
	return &meetingServiceClient{cc}
}

func (c *meetingServiceClient) CreateMeeting(ctx context.Context, in *CreateMeetingRequest, opts ...grpc.CallOption) (*CreateMeetingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMeetingResponse)
	err := c.cc.Invoke(ctx, MeetingService_CreateMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) StopMeeting(ctx context.Context, in *StopMeetingRequest, opts ...grpc.CallOption) (*StopMeetingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopMeetingResponse)
	err := c.cc.Invoke(ctx, MeetingService_StopMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) GetMeeting(ctx context.Context, in *GetMeetingRequest, opts ...grpc.CallOption) (*GetMeetingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMeetingResponse)
	err := c.cc.Invoke(ctx, MeetingService_GetMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) ListTranscriptSegments(ctx context.Context, in *ListTranscriptSegmentsRequest, opts ...grpc.CallOption) (*ListTranscriptSegmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTranscriptSegmentsResponse)
	err := c.cc.Invoke(ctx, MeetingService_ListTranscriptSegments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) GetMeetingSummary(ctx context.Context, in *GetMeetingSummaryRequest, opts ...grpc.CallOption) (*GetMeetingSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMeetingSummaryResponse)
	err := c.cc.Invoke(ctx, MeetingService_GetMeetingSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) RegenerateMeetingSummary(ctx context.Context, in *RegenerateMeetingSummaryRequest, opts ...grpc.CallOption) (*RegenerateMeetingSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegenerateMeetingSummaryResponse)
	err := c.cc.Invoke(ctx, MeetingService_RegenerateMeetingSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingServiceClient) GetMeetingQuota(ctx context.Context, in *GetMeetingQuotaRequest, opts ...grpc.CallOption) (*GetMeetingQuotaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMeetingQuotaResponse)
	err := c.cc.Invoke(ctx, MeetingService_GetMeetingQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeetingServiceServer is the server API for MeetingService service.
// All implementations must embed UnimplementedMeetingServiceServer
// for forward compatibility.
//
// MeetingService 提供当前登录用户的会议控制、额度和最终转写查询能力。
type MeetingServiceServer interface {
	// CreateMeeting 创建并开始会议；HTTP 调用必须携带 Idempotency-Key。
	CreateMeeting(context.Context, *CreateMeetingRequest) (*CreateMeetingResponse, error)
	// StopMeeting 幂等停止会议；HTTP 调用必须携带 Idempotency-Key。
	StopMeeting(context.Context, *StopMeetingRequest) (*StopMeetingResponse, error)
	// GetMeeting 查询当前用户拥有的会议及转写阶段状态。
	GetMeeting(context.Context, *GetMeetingRequest) (*GetMeetingResponse, error)
	// ListTranscriptSegments 分页查询会议的最终转写片段。
	ListTranscriptSegments(context.Context, *ListTranscriptSegmentsRequest) (*ListTranscriptSegmentsResponse, error)
	// GetMeetingSummary 查询当前会议最新可展示的结构化纪要及生成状态。
	GetMeetingSummary(context.Context, *GetMeetingSummaryRequest) (*GetMeetingSummaryResponse, error)
	// RegenerateMeetingSummary 基于当前最终转写版本异步重新生成纪要；HTTP 调用必须携带 Idempotency-Key。
	RegenerateMeetingSummary(context.Context, *RegenerateMeetingSummaryRequest) (*RegenerateMeetingSummaryResponse, error)
	// GetMeetingQuota 查询当前用户在本计费周期的会议额度。
	GetMeetingQuota(context.Context, *GetMeetingQuotaRequest) (*GetMeetingQuotaResponse, error)
	mustEmbedUnimplementedMeetingServiceServer()
}

// UnimplementedMeetingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeetingServiceServer struct{}

func (UnimplementedMeetingServiceServer) CreateMeeting(context.Context, *CreateMeetingRequest) (*CreateMeetingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMeeting not implemented")
}
func (UnimplementedMeetingServiceServer) StopMeeting(context.Context, *StopMeetingRequest) (*StopMeetingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopMeeting not implemented")
}
func (UnimplementedMeetingServiceServer) GetMeeting(context.Context, *GetMeetingRequest) (*GetMeetingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMeeting not implemented")
}
func (UnimplementedMeetingServiceServer) ListTranscriptSegments(context.Context, *ListTranscriptSegmentsRequest) (*ListTranscriptSegmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTranscriptSegments not implemented")
}
func (UnimplementedMeetingServiceServer) GetMeetingSummary(context.Context, *GetMeetingSummaryRequest) (*GetMeetingSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMeetingSummary not implemented")
}
func (UnimplementedMeetingServiceServer) RegenerateMeetingSummary(context.Context, *RegenerateMeetingSummaryRequest) (*RegenerateMeetingSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegenerateMeetingSummary not implemented")
}
func (UnimplementedMeetingServiceServer) GetMeetingQuota(context.Context, *GetMeetingQuotaRequest) (*GetMeetingQuotaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMeetingQuota not implemented")
}
func (UnimplementedMeetingServiceServer) mustEmbedUnimplementedMeetingServiceServer() {}
func (UnimplementedMeetingServiceServer) testEmbeddedByValue()                        {}

// UnsafeMeetingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeetingServiceServer will
// result in compilation errors.
type UnsafeMeetingServiceServer interface {
	mustEmbedUnimplementedMeetingServiceServer()
}

func RegisterMeetingServiceServer(s grpc.ServiceRegistrar, srv MeetingServiceServer) {
	// If the following call panics, it indicates UnimplementedMeetingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MeetingService_ServiceDesc, srv)
}

func _MeetingService_CreateMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMeetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).CreateMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_CreateMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).CreateMeeting(ctx, req.(*CreateMeetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_StopMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopMeetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).StopMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_StopMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).StopMeeting(ctx, req.(*StopMeetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_GetMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).GetMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_GetMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).GetMeeting(ctx, req.(*GetMeetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_ListTranscriptSegments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTranscriptSegmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).ListTranscriptSegments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_ListTranscriptSegments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).ListTranscriptSegments(ctx, req.(*ListTranscriptSegmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_GetMeetingSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeetingSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).GetMeetingSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_GetMeetingSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).GetMeetingSummary(ctx, req.(*GetMeetingSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_RegenerateMeetingSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegenerateMeetingSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).RegenerateMeetingSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_RegenerateMeetingSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).RegenerateMeetingSummary(ctx, req.(*RegenerateMeetingSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingService_GetMeetingQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeetingQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).GetMeetingQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingService_GetMeetingQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).GetMeetingQuota(ctx, req.(*GetMeetingQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MeetingService_ServiceDesc is the grpc.ServiceDesc for MeetingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeetingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meeting.v1.MeetingService",
	HandlerType: (*MeetingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMeeting",
			Handler:    _MeetingService_CreateMeeting_Handler,
		},
		{
			MethodName: "StopMeeting",
			Handler:    _MeetingService_StopMeeting_Handler,
		},
		{
			MethodName: "GetMeeting",
			Handler:    _MeetingService_GetMeeting_Handler,
		},
		{
			MethodName: "ListTranscriptSegments",
			Handler:    _MeetingService_ListTranscriptSegments_Handler,
		},
		{
			MethodName: "GetMeetingSummary",
			Handler:    _MeetingService_GetMeetingSummary_Handler,
		},
		{
			MethodName: "RegenerateMeetingSummary",
			Handler:    _MeetingService_RegenerateMeetingSummary_Handler,
		},
		{
			MethodName: "GetMeetingQuota",
			Handler:    _MeetingService_GetMeetingQuota_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meeting/v1/meeting.proto",
}
