// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: meeting/v1/meeting_internal.proto

package meetingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MeetingIngestInternalService_AppendFinalTranscriptSegments_FullMethodName = "/meeting.v1.MeetingIngestInternalService/AppendFinalTranscriptSegments"
	MeetingIngestInternalService_ReportTranscriptionUsage_FullMethodName      = "/meeting.v1.MeetingIngestInternalService/ReportTranscriptionUsage"
	MeetingIngestInternalService_CompleteTranscription_FullMethodName         = "/meeting.v1.MeetingIngestInternalService/CompleteTranscription"
	MeetingIngestInternalService_FailTranscription_FullMethodName             = "/meeting.v1.MeetingIngestInternalService/FailTranscription"
	MeetingIngestInternalService_GetMeetingTranscriptSnapshot_FullMethodName  = "/meeting.v1.MeetingIngestInternalService/GetMeetingTranscriptSnapshot"
	MeetingIngestInternalService_CompleteMeetingSummary_FullMethodName        = "/meeting.v1.MeetingIngestInternalService/CompleteMeetingSummary"
	MeetingIngestInternalService_FailMeetingSummary_FullMethodName            = "/meeting.v1.MeetingIngestInternalService/FailMeetingSummary"
)

// MeetingIngestInternalServiceClient is the client API for MeetingIngestInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MeetingIngestInternalService 提供 vision-service 到 core-service 的内部转写结果和用量写入能力。
type MeetingIngestInternalServiceClient interface {
	// AppendFinalTranscriptSegments 幂等批量追加已经最终确认的转写片段。
	AppendFinalTranscriptSegments(ctx context.Context, in *AppendFinalTranscriptSegmentsRequest, opts ...grpc.CallOption) (*AppendFinalTranscriptSegmentsResponse, error)
	// ReportTranscriptionUsage 幂等上报 vision-service 已接受的累计音频时长。
	ReportTranscriptionUsage(ctx context.Context, in *ReportTranscriptionUsageRequest, opts ...grpc.CallOption) (*ReportTranscriptionUsageResponse, error)
	// CompleteTranscription 幂等完成转写并结算用户额度预占。
	CompleteTranscription(ctx context.Context, in *CompleteTranscriptionRequest, opts ...grpc.CallOption) (*CompleteTranscriptionResponse, error)
	// FailTranscription 幂等记录转写失败并结算用户额度预占。
	FailTranscription(ctx context.Context, in *FailTranscriptionRequest, opts ...grpc.CallOption) (*FailTranscriptionResponse, error)
	// GetMeetingTranscriptSnapshot 返回指定版本的完整最终转写，供 vision 生成纪要。
	GetMeetingTranscriptSnapshot(ctx context.Context, in *GetMeetingTranscriptSnapshotRequest, opts ...grpc.CallOption) (*GetMeetingTranscriptSnapshotResponse, error)
	// CompleteMeetingSummary 幂等保存经过校验的会议纪要。
	CompleteMeetingSummary(ctx context.Context, in *CompleteMeetingSummaryRequest, opts ...grpc.CallOption) (*CompleteMeetingSummaryResponse, error)
	// FailMeetingSummary 幂等记录会议纪要生成失败。
	FailMeetingSummary(ctx context.Context, in *FailMeetingSummaryRequest, opts ...grpc.CallOption) (*FailMeetingSummaryResponse, error)
}

type meetingIngestInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeetingIngestInternalServiceClient(cc grpc.ClientConnInterface) MeetingIngestInternalServiceClient {
	return &meetingIngestInternalServiceClient{cc}
}

func (c *meetingIngestInternalServiceClient) AppendFinalTranscriptSegments(ctx context.Context, in *AppendFinalTranscriptSegmentsRequest, opts ...grpc.CallOption) (*AppendFinalTranscriptSegmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendFinalTranscriptSegmentsResponse)
	err := c.cc.Invoke(ctx, MeetingIngestInternalService_AppendFinalTranscriptSegments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingIngestInternalServiceClient) ReportTranscriptionUsage(ctx context.Context, in *ReportTranscriptionUsageRequest, opts ...grpc.CallOption) (*ReportTranscriptionUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportTranscriptionUsageResponse)
	err := c.cc.Invoke(ctx, MeetingIngestInternalService_ReportTranscriptionUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingIngestInternalServiceClient) CompleteTranscription(ctx context.Context, in *CompleteTranscriptionRequest, opts ...grpc.CallOption) (*CompleteTranscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteTranscriptionResponse)
	err := c.cc.Invoke(ctx, MeetingIngestInternalService_CompleteTranscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingIngestInternalServiceClient) FailTranscription(ctx context.Context, in *FailTranscriptionRequest, opts ...grpc.CallOption) (*FailTranscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FailTranscriptionResponse)
	err := c.cc.Invoke(ctx, MeetingIngestInternalService_FailTranscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingIngestInternalServiceClient) GetMeetingTranscriptSnapshot(ctx context.Context, in *GetMeetingTranscriptSnapshotRequest, opts ...grpc.CallOption) (*GetMeetingTranscriptSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMeetingTranscriptSnapshotResponse)
	err := c.cc.Invoke(ctx, MeetingIngestInternalService_GetMeetingTranscriptSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingIngestInternalServiceClient) CompleteMeetingSummary(ctx context.Context, in *CompleteMeetingSummaryRequest, opts ...grpc.CallOption) (*CompleteMeetingSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteMeetingSummaryResponse)
	err := c.cc.Invoke(ctx, MeetingIngestInternalService_CompleteMeetingSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingIngestInternalServiceClient) FailMeetingSummary(ctx context.Context, in *FailMeetingSummaryRequest, opts ...grpc.CallOption) (*FailMeetingSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FailMeetingSummaryResponse)
	err := c.cc.Invoke(ctx, MeetingIngestInternalService_FailMeetingSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeetingIngestInternalServiceServer is the server API for MeetingIngestInternalService service.
// All implementations must embed UnimplementedMeetingIngestInternalServiceServer
// for forward compatibility.
//
// MeetingIngestInternalService 提供 vision-service 到 core-service 的内部转写结果和用量写入能力。
type MeetingIngestInternalServiceServer interface {
	// AppendFinalTranscriptSegments 幂等批量追加已经最终确认的转写片段。
	AppendFinalTranscriptSegments(context.Context, *AppendFinalTranscriptSegmentsRequest) (*AppendFinalTranscriptSegmentsResponse, error)
	// ReportTranscriptionUsage 幂等上报 vision-service 已接受的累计音频时长。
	ReportTranscriptionUsage(context.Context, *ReportTranscriptionUsageRequest) (*ReportTranscriptionUsageResponse, error)
	// CompleteTranscription 幂等完成转写并结算用户额度预占。
	CompleteTranscription(context.Context, *CompleteTranscriptionRequest) (*CompleteTranscriptionResponse, error)
	// FailTranscription 幂等记录转写失败并结算用户额度预占。
	FailTranscription(context.Context, *FailTranscriptionRequest) (*FailTranscriptionResponse, error)
	// GetMeetingTranscriptSnapshot 返回指定版本的完整最终转写，供 vision 生成纪要。
	GetMeetingTranscriptSnapshot(context.Context, *GetMeetingTranscriptSnapshotRequest) (*GetMeetingTranscriptSnapshotResponse, error)
	// CompleteMeetingSummary 幂等保存经过校验的会议纪要。
	CompleteMeetingSummary(context.Context, *CompleteMeetingSummaryRequest) (*CompleteMeetingSummaryResponse, error)
	// FailMeetingSummary 幂等记录会议纪要生成失败。
	FailMeetingSummary(context.Context, *FailMeetingSummaryRequest) (*FailMeetingSummaryResponse, error)
	mustEmbedUnimplementedMeetingIngestInternalServiceServer()
}

// UnimplementedMeetingIngestInternalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeetingIngestInternalServiceServer struct{}

func (UnimplementedMeetingIngestInternalServiceServer) AppendFinalTranscriptSegments(context.Context, *AppendFinalTranscriptSegmentsRequest) (*AppendFinalTranscriptSegmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendFinalTranscriptSegments not implemented")
}
func (UnimplementedMeetingIngestInternalServiceServer) ReportTranscriptionUsage(context.Context, *ReportTranscriptionUsageRequest) (*ReportTranscriptionUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTranscriptionUsage not implemented")
}
func (UnimplementedMeetingIngestInternalServiceServer) CompleteTranscription(context.Context, *CompleteTranscriptionRequest) (*CompleteTranscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteTranscription not implemented")
}
func (UnimplementedMeetingIngestInternalServiceServer) FailTranscription(context.Context, *FailTranscriptionRequest) (*FailTranscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FailTranscription not implemented")
}
func (UnimplementedMeetingIngestInternalServiceServer) GetMeetingTranscriptSnapshot(context.Context, *GetMeetingTranscriptSnapshotRequest) (*GetMeetingTranscriptSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMeetingTranscriptSnapshot not implemented")
}
func (UnimplementedMeetingIngestInternalServiceServer) CompleteMeetingSummary(context.Context, *CompleteMeetingSummaryRequest) (*CompleteMeetingSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteMeetingSummary not implemented")
}
func (UnimplementedMeetingIngestInternalServiceServer) FailMeetingSummary(context.Context, *FailMeetingSummaryRequest) (*FailMeetingSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FailMeetingSummary not implemented")
}
func (UnimplementedMeetingIngestInternalServiceServer) mustEmbedUnimplementedMeetingIngestInternalServiceServer() {
}
func (UnimplementedMeetingIngestInternalServiceServer) testEmbeddedByValue() {}

// UnsafeMeetingIngestInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeetingIngestInternalServiceServer will
// result in compilation errors.
type UnsafeMeetingIngestInternalServiceServer interface {
	mustEmbedUnimplementedMeetingIngestInternalServiceServer()
}

func RegisterMeetingIngestInternalServiceServer(s grpc.ServiceRegistrar, srv MeetingIngestInternalServiceServer) {
	// If the following call panics, it indicates UnimplementedMeetingIngestInternalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MeetingIngestInternalService_ServiceDesc, srv)
}

func _MeetingIngestInternalService_AppendFinalTranscriptSegments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendFinalTranscriptSegmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingIngestInternalServiceServer).AppendFinalTranscriptSegments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingIngestInternalService_AppendFinalTranscriptSegments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingIngestInternalServiceServer).AppendFinalTranscriptSegments(ctx, req.(*AppendFinalTranscriptSegmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingIngestInternalService_ReportTranscriptionUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportTranscriptionUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingIngestInternalServiceServer).ReportTranscriptionUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingIngestInternalService_ReportTranscriptionUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingIngestInternalServiceServer).ReportTranscriptionUsage(ctx, req.(*ReportTranscriptionUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingIngestInternalService_CompleteTranscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteTranscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingIngestInternalServiceServer).CompleteTranscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingIngestInternalService_CompleteTranscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingIngestInternalServiceServer).CompleteTranscription(ctx, req.(*CompleteTranscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingIngestInternalService_FailTranscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailTranscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingIngestInternalServiceServer).FailTranscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingIngestInternalService_FailTranscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingIngestInternalServiceServer).FailTranscription(ctx, req.(*FailTranscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingIngestInternalService_GetMeetingTranscriptSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeetingTranscriptSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingIngestInternalServiceServer).GetMeetingTranscriptSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingIngestInternalService_GetMeetingTranscriptSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingIngestInternalServiceServer).GetMeetingTranscriptSnapshot(ctx, req.(*GetMeetingTranscriptSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingIngestInternalService_CompleteMeetingSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteMeetingSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingIngestInternalServiceServer).CompleteMeetingSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingIngestInternalService_CompleteMeetingSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingIngestInternalServiceServer).CompleteMeetingSummary(ctx, req.(*CompleteMeetingSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingIngestInternalService_FailMeetingSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailMeetingSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingIngestInternalServiceServer).FailMeetingSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingIngestInternalService_FailMeetingSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingIngestInternalServiceServer).FailMeetingSummary(ctx, req.(*FailMeetingSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MeetingIngestInternalService_ServiceDesc is the grpc.ServiceDesc for MeetingIngestInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeetingIngestInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meeting.v1.MeetingIngestInternalService",
	HandlerType: (*MeetingIngestInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendFinalTranscriptSegments",
			Handler:    _MeetingIngestInternalService_AppendFinalTranscriptSegments_Handler,
		},
		{
			MethodName: "ReportTranscriptionUsage",
			Handler:    _MeetingIngestInternalService_ReportTranscriptionUsage_Handler,
		},
		{
			MethodName: "CompleteTranscription",
			Handler:    _MeetingIngestInternalService_CompleteTranscription_Handler,
		},
		{
			MethodName: "FailTranscription",
			Handler:    _MeetingIngestInternalService_FailTranscription_Handler,
		},
		{
			MethodName: "GetMeetingTranscriptSnapshot",
			Handler:    _MeetingIngestInternalService_GetMeetingTranscriptSnapshot_Handler,
		},
		{
			MethodName: "CompleteMeetingSummary",
			Handler:    _MeetingIngestInternalService_CompleteMeetingSummary_Handler,
		},
		{
			MethodName: "FailMeetingSummary",
			Handler:    _MeetingIngestInternalService_FailMeetingSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meeting/v1/meeting_internal.proto",
}
