// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: meeting/v1/meeting.proto

package meetingv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationMeetingServiceCreateMeeting = "/meeting.v1.MeetingService/CreateMeeting"
const OperationMeetingServiceGetMeeting = "/meeting.v1.MeetingService/GetMeeting"
const OperationMeetingServiceGetMeetingQuota = "/meeting.v1.MeetingService/GetMeetingQuota"
const OperationMeetingServiceGetMeetingSummary = "/meeting.v1.MeetingService/GetMeetingSummary"
const OperationMeetingServiceListTranscriptSegments = "/meeting.v1.MeetingService/ListTranscriptSegments"
const OperationMeetingServiceRegenerateMeetingSummary = "/meeting.v1.MeetingService/RegenerateMeetingSummary"
const OperationMeetingServiceStopMeeting = "/meeting.v1.MeetingService/StopMeeting"

type MeetingServiceHTTPServer interface {
	// CreateMeeting CreateMeeting 创建并开始会议；HTTP 调用必须携带 Idempotency-Key。
	CreateMeeting(context.Context, *CreateMeetingRequest) (*CreateMeetingResponse, error)
	// GetMeeting GetMeeting 查询当前用户拥有的会议及转写阶段状态。
	GetMeeting(context.Context, *GetMeetingRequest) (*GetMeetingResponse, error)
	// GetMeetingQuota GetMeetingQuota 查询当前用户在本计费周期的会议额度。
	GetMeetingQuota(context.Context, *GetMeetingQuotaRequest) (*GetMeetingQuotaResponse, error)
	// GetMeetingSummary GetMeetingSummary 查询当前会议最新可展示的结构化纪要及生成状态。
	GetMeetingSummary(context.Context, *GetMeetingSummaryRequest) (*GetMeetingSummaryResponse, error)
	// ListTranscriptSegments ListTranscriptSegments 分页查询会议的最终转写片段。
	ListTranscriptSegments(context.Context, *ListTranscriptSegmentsRequest) (*ListTranscriptSegmentsResponse, error)
	// RegenerateMeetingSummary RegenerateMeetingSummary 基于当前最终转写版本异步重新生成纪要；HTTP 调用必须携带 Idempotency-Key。
	RegenerateMeetingSummary(context.Context, *RegenerateMeetingSummaryRequest) (*RegenerateMeetingSummaryResponse, error)
	// StopMeeting StopMeeting 幂等停止会议；HTTP 调用必须携带 Idempotency-Key。
	StopMeeting(context.Context, *StopMeetingRequest) (*StopMeetingResponse, error)
}

func RegisterMeetingServiceHTTPServer(s *http.Server, srv MeetingServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/meetings", _MeetingService_CreateMeeting0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/meetings/{meeting_id}:stop", _MeetingService_StopMeeting0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/meetings/{meeting_id}", _MeetingService_GetMeeting0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/meetings/{meeting_id}/transcript-segments", _MeetingService_ListTranscriptSegments0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/meetings/{meeting_id}/summary", _MeetingService_GetMeetingSummary0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/meetings/{meeting_id}/summary:regenerate", _MeetingService_RegenerateMeetingSummary0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/meeting-quota", _MeetingService_GetMeetingQuota0_HTTP_Handler(srv))
}

func _MeetingService_CreateMeeting0_HTTP_Handler(srv MeetingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateMeetingRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMeetingServiceCreateMeeting)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateMeeting(ctx, req.(*CreateMeetingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateMeetingResponse)
		return ctx.Result(200, reply)
	}
}

func _MeetingService_StopMeeting0_HTTP_Handler(srv MeetingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StopMeetingRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMeetingServiceStopMeeting)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StopMeeting(ctx, req.(*StopMeetingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StopMeetingResponse)
		return ctx.Result(200, reply)
	}
}

func _MeetingService_GetMeeting0_HTTP_Handler(srv MeetingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMeetingRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMeetingServiceGetMeeting)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMeeting(ctx, req.(*GetMeetingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMeetingResponse)
		return ctx.Result(200, reply)
	}
}

func _MeetingService_ListTranscriptSegments0_HTTP_Handler(srv MeetingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTranscriptSegmentsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMeetingServiceListTranscriptSegments)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTranscriptSegments(ctx, req.(*ListTranscriptSegmentsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTranscriptSegmentsResponse)
		return ctx.Result(200, reply)
	}
}

func _MeetingService_GetMeetingSummary0_HTTP_Handler(srv MeetingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMeetingSummaryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMeetingServiceGetMeetingSummary)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMeetingSummary(ctx, req.(*GetMeetingSummaryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMeetingSummaryResponse)
		return ctx.Result(200, reply)
	}
}

func _MeetingService_RegenerateMeetingSummary0_HTTP_Handler(srv MeetingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RegenerateMeetingSummaryRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMeetingServiceRegenerateMeetingSummary)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RegenerateMeetingSummary(ctx, req.(*RegenerateMeetingSummaryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RegenerateMeetingSummaryResponse)
		return ctx.Result(200, reply)
	}
}

func _MeetingService_GetMeetingQuota0_HTTP_Handler(srv MeetingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMeetingQuotaRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMeetingServiceGetMeetingQuota)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMeetingQuota(ctx, req.(*GetMeetingQuotaRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMeetingQuotaResponse)
		return ctx.Result(200, reply)
	}
}

type MeetingServiceHTTPClient interface {
	// CreateMeeting CreateMeeting 创建并开始会议；HTTP 调用必须携带 Idempotency-Key。
	CreateMeeting(ctx context.Context, req *CreateMeetingRequest, opts ...http.CallOption) (rsp *CreateMeetingResponse, err error)
	// GetMeeting GetMeeting 查询当前用户拥有的会议及转写阶段状态。
	GetMeeting(ctx context.Context, req *GetMeetingRequest, opts ...http.CallOption) (rsp *GetMeetingResponse, err error)
	// GetMeetingQuota GetMeetingQuota 查询当前用户在本计费周期的会议额度。
	GetMeetingQuota(ctx context.Context, req *GetMeetingQuotaRequest, opts ...http.CallOption) (rsp *GetMeetingQuotaResponse, err error)
	// GetMeetingSummary GetMeetingSummary 查询当前会议最新可展示的结构化纪要及生成状态。
	GetMeetingSummary(ctx context.Context, req *GetMeetingSummaryRequest, opts ...http.CallOption) (rsp *GetMeetingSummaryResponse, err error)
	// ListTranscriptSegments ListTranscriptSegments 分页查询会议的最终转写片段。
	ListTranscriptSegments(ctx context.Context, req *ListTranscriptSegmentsRequest, opts ...http.CallOption) (rsp *ListTranscriptSegmentsResponse, err error)
	// RegenerateMeetingSummary RegenerateMeetingSummary 基于当前最终转写版本异步重新生成纪要；HTTP 调用必须携带 Idempotency-Key。
	RegenerateMeetingSummary(ctx context.Context, req *RegenerateMeetingSummaryRequest, opts ...http.CallOption) (rsp *RegenerateMeetingSummaryResponse, err error)
	// StopMeeting StopMeeting 幂等停止会议；HTTP 调用必须携带 Idempotency-Key。
	StopMeeting(ctx context.Context, req *StopMeetingRequest, opts ...http.CallOption) (rsp *StopMeetingResponse, err error)
}

type MeetingServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewMeetingServiceHTTPClient(client *http.Client) MeetingServiceHTTPClient {
	return &MeetingServiceHTTPClientImpl{client}
}

// CreateMeeting CreateMeeting 创建并开始会议；HTTP 调用必须携带 Idempotency-Key。
func (c *MeetingServiceHTTPClientImpl) CreateMeeting(ctx context.Context, in *CreateMeetingRequest, opts ...http.CallOption) (*CreateMeetingResponse, error) {
	var out CreateMeetingResponse
	pattern := "/v1/meetings"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationMeetingServiceCreateMeeting),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMeeting GetMeeting 查询当前用户拥有的会议及转写阶段状态。
func (c *MeetingServiceHTTPClientImpl) GetMeeting(ctx context.Context, in *GetMeetingRequest, opts ...http.CallOption) (*GetMeetingResponse, error) {
	var out GetMeetingResponse
	pattern := "/v1/meetings/{meeting_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationMeetingServiceGetMeeting),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMeetingQuota GetMeetingQuota 查询当前用户在本计费周期的会议额度。
func (c *MeetingServiceHTTPClientImpl) GetMeetingQuota(ctx context.Context, in *GetMeetingQuotaRequest, opts ...http.CallOption) (*GetMeetingQuotaResponse, error) {
	var out GetMeetingQuotaResponse
	pattern := "/v1/meeting-quota"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationMeetingServiceGetMeetingQuota),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMeetingSummary GetMeetingSummary 查询当前会议最新可展示的结构化纪要及生成状态。
func (c *MeetingServiceHTTPClientImpl) GetMeetingSummary(ctx context.Context, in *GetMeetingSummaryRequest, opts ...http.CallOption) (*GetMeetingSummaryResponse, error) {
	var out GetMeetingSummaryResponse
	pattern := "/v1/meetings/{meeting_id}/summary"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationMeetingServiceGetMeetingSummary),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListTranscriptSegments ListTranscriptSegments 分页查询会议的最终转写片段。
func (c *MeetingServiceHTTPClientImpl) ListTranscriptSegments(ctx context.Context, in *ListTranscriptSegmentsRequest, opts ...http.CallOption) (*ListTranscriptSegmentsResponse, error) {
	var out ListTranscriptSegmentsResponse
	pattern := "/v1/meetings/{meeting_id}/transcript-segments"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationMeetingServiceListTranscriptSegments),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RegenerateMeetingSummary RegenerateMeetingSummary 基于当前最终转写版本异步重新生成纪要；HTTP 调用必须携带 Idempotency-Key。
func (c *MeetingServiceHTTPClientImpl) RegenerateMeetingSummary(ctx context.Context, in *RegenerateMeetingSummaryRequest, opts ...http.CallOption) (*RegenerateMeetingSummaryResponse, error) {
	var out RegenerateMeetingSummaryResponse
	pattern := "/v1/meetings/{meeting_id}/summary:regenerate"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationMeetingServiceRegenerateMeetingSummary),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// StopMeeting StopMeeting 幂等停止会议；HTTP 调用必须携带 Idempotency-Key。
func (c *MeetingServiceHTTPClientImpl) StopMeeting(ctx context.Context, in *StopMeetingRequest, opts ...http.CallOption) (*StopMeetingResponse, error) {
	var out StopMeetingResponse
	pattern := "/v1/meetings/{meeting_id}:stop"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationMeetingServiceStopMeeting),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
