// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: meeting/v1/meeting_internal.proto

package meetingv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MeetingSummaryFailureReason 表示可以安全跨服务传播的纪要失败分类。
type MeetingSummaryFailureReason int32

const (
	// 未指定失败原因。
	MeetingSummaryFailureReason_MEETING_SUMMARY_FAILURE_REASON_UNSPECIFIED MeetingSummaryFailureReason = 0
	// LLM Provider 暂时不可用。
	MeetingSummaryFailureReason_MEETING_SUMMARY_FAILURE_REASON_PROVIDER_UNAVAILABLE MeetingSummaryFailureReason = 1
	// LLM Provider 拒绝请求。
	MeetingSummaryFailureReason_MEETING_SUMMARY_FAILURE_REASON_PROVIDER_REJECTED MeetingSummaryFailureReason = 2
	// Provider 输出不符合结构或大小约束。
	MeetingSummaryFailureReason_MEETING_SUMMARY_FAILURE_REASON_OUTPUT_INVALID MeetingSummaryFailureReason = 3
	// 最终转写为空或版本不匹配。
	MeetingSummaryFailureReason_MEETING_SUMMARY_FAILURE_REASON_TRANSCRIPT_INVALID MeetingSummaryFailureReason = 4
	// 生成任务超过截止时间。
	MeetingSummaryFailureReason_MEETING_SUMMARY_FAILURE_REASON_TIMEOUT MeetingSummaryFailureReason = 5
	// 已脱敏的未知内部失败。
	MeetingSummaryFailureReason_MEETING_SUMMARY_FAILURE_REASON_INTERNAL MeetingSummaryFailureReason = 6
)

// Enum value maps for MeetingSummaryFailureReason.
var (
	MeetingSummaryFailureReason_name = map[int32]string{
		0: "MEETING_SUMMARY_FAILURE_REASON_UNSPECIFIED",
		1: "MEETING_SUMMARY_FAILURE_REASON_PROVIDER_UNAVAILABLE",
		2: "MEETING_SUMMARY_FAILURE_REASON_PROVIDER_REJECTED",
		3: "MEETING_SUMMARY_FAILURE_REASON_OUTPUT_INVALID",
		4: "MEETING_SUMMARY_FAILURE_REASON_TRANSCRIPT_INVALID",
		5: "MEETING_SUMMARY_FAILURE_REASON_TIMEOUT",
		6: "MEETING_SUMMARY_FAILURE_REASON_INTERNAL",
	}
	MeetingSummaryFailureReason_value = map[string]int32{
		"MEETING_SUMMARY_FAILURE_REASON_UNSPECIFIED":          0,
		"MEETING_SUMMARY_FAILURE_REASON_PROVIDER_UNAVAILABLE": 1,
		"MEETING_SUMMARY_FAILURE_REASON_PROVIDER_REJECTED":    2,
		"MEETING_SUMMARY_FAILURE_REASON_OUTPUT_INVALID":       3,
		"MEETING_SUMMARY_FAILURE_REASON_TRANSCRIPT_INVALID":   4,
		"MEETING_SUMMARY_FAILURE_REASON_TIMEOUT":              5,
		"MEETING_SUMMARY_FAILURE_REASON_INTERNAL":             6,
	}
)

func (x MeetingSummaryFailureReason) Enum() *MeetingSummaryFailureReason {
	p := new(MeetingSummaryFailureReason)
	*p = x
	return p
}

func (x MeetingSummaryFailureReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MeetingSummaryFailureReason) Descriptor() protoreflect.EnumDescriptor {
	return file_meeting_v1_meeting_internal_proto_enumTypes[0].Descriptor()
}

func (MeetingSummaryFailureReason) Type() protoreflect.EnumType {
	return &file_meeting_v1_meeting_internal_proto_enumTypes[0]
}

func (x MeetingSummaryFailureReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MeetingSummaryFailureReason.Descriptor instead.
func (MeetingSummaryFailureReason) EnumDescriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_internal_proto_rawDescGZIP(), []int{0}
}

// TranscriptionFailureReason 表示可安全跨服务传播的稳定转写失败分类。
type TranscriptionFailureReason int32

const (
	// 未指定失败原因。
	TranscriptionFailureReason_TRANSCRIPTION_FAILURE_REASON_UNSPECIFIED TranscriptionFailureReason = 0
	// ASR Provider 暂时不可用。
	TranscriptionFailureReason_TRANSCRIPTION_FAILURE_REASON_PROVIDER_UNAVAILABLE TranscriptionFailureReason = 1
	// ASR Provider 因权限、参数或配额拒绝任务。
	TranscriptionFailureReason_TRANSCRIPTION_FAILURE_REASON_PROVIDER_REJECTED TranscriptionFailureReason = 2
	// 音频格式或内容不符合约束。
	TranscriptionFailureReason_TRANSCRIPTION_FAILURE_REASON_AUDIO_INVALID TranscriptionFailureReason = 3
	// 转写任务超过内部截止时间。
	TranscriptionFailureReason_TRANSCRIPTION_FAILURE_REASON_TIMEOUT TranscriptionFailureReason = 4
	// 用户额度已经耗尽。
	TranscriptionFailureReason_TRANSCRIPTION_FAILURE_REASON_QUOTA_EXHAUSTED TranscriptionFailureReason = 5
	// 会话被取消。
	TranscriptionFailureReason_TRANSCRIPTION_FAILURE_REASON_CANCELLED TranscriptionFailureReason = 6
	// 已脱敏的未知内部失败。
	TranscriptionFailureReason_TRANSCRIPTION_FAILURE_REASON_INTERNAL TranscriptionFailureReason = 7
)

// Enum value maps for TranscriptionFailureReason.
var (
	TranscriptionFailureReason_name = map[int32]string{
		0: "TRANSCRIPTION_FAILURE_REASON_UNSPECIFIED",
		1: "TRANSCRIPTION_FAILURE_REASON_PROVIDER_UNAVAILABLE",
		2: "TRANSCRIPTION_FAILURE_REASON_PROVIDER_REJECTED",
		3: "TRANSCRIPTION_FAILURE_REASON_AUDIO_INVALID",
		4: "TRANSCRIPTION_FAILURE_REASON_TIMEOUT",
		5: "TRANSCRIPTION_FAILURE_REASON_QUOTA_EXHAUSTED",
		6: "TRANSCRIPTION_FAILURE_REASON_CANCELLED",
		7: "TRANSCRIPTION_FAILURE_REASON_INTERNAL",
	}
	TranscriptionFailureReason_value = map[string]int32{
		"TRANSCRIPTION_FAILURE_REASON_UNSPECIFIED":          0,
		"TRANSCRIPTION_FAILURE_REASON_PROVIDER_UNAVAILABLE": 1,
		"TRANSCRIPTION_FAILURE_REASON_PROVIDER_REJECTED":    2,
		"TRANSCRIPTION_FAILURE_REASON_AUDIO_INVALID":        3,
		"TRANSCRIPTION_FAILURE_REASON_TIMEOUT":              4,
		"TRANSCRIPTION_FAILURE_REASON_QUOTA_EXHAUSTED":      5,
		"TRANSCRIPTION_FAILURE_REASON_CANCELLED":            6,
		"TRANSCRIPTION_FAILURE_REASON_INTERNAL":             7,
	}
)

func (x TranscriptionFailureReason) Enum() *TranscriptionFailureReason {
	p := new(TranscriptionFailureReason)
	*p = x
	return p
}

func (x TranscriptionFailureReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TranscriptionFailureReason) Descriptor() protoreflect.EnumDescriptor {
	return file_meeting_v1_meeting_internal_proto_enumTypes[1].Descriptor()
}

func (TranscriptionFailureReason) Type() protoreflect.EnumType {
	return &file_meeting_v1_meeting_internal_proto_enumTypes[1]
}

func (x TranscriptionFailureReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TranscriptionFailureReason.Descriptor instead.
func (TranscriptionFailureReason) EnumDescriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_internal_proto_rawDescGZIP(), []int{1}
}

// AppendFinalTranscriptSegmentsRequest 是追加最终片段的内部参数。
type AppendFinalTranscriptSegmentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// core-service 会议 UUID。
	MeetingId string `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	// vision-service 转写会话 UUID。
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// 本批次的稳定 UUID；重试时保持不变。
	BatchId string `protobuf:"bytes,3,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	// 按 sequence_no 升序排列的最终片段。
	Segments      []*TranscriptSegment `protobuf:"bytes,4,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendFinalTranscriptSegmentsRequest) Reset() {
	*x = AppendFinalTranscriptSegmentsRequest{}
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendFinalTranscriptSegmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendFinalTranscriptSegmentsRequest) ProtoMessage() {}

func (x *AppendFinalTranscriptSegmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendFinalTranscriptSegmentsRequest.ProtoReflect.Descriptor instead.
func (*AppendFinalTranscriptSegmentsRequest) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_internal_proto_rawDescGZIP(), []int{0}
}

func (x *AppendFinalTranscriptSegmentsRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *AppendFinalTranscriptSegmentsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AppendFinalTranscriptSegmentsRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *AppendFinalTranscriptSegmentsRequest) GetSegments() []*TranscriptSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

// AppendFinalTranscriptSegmentsResponse 返回 core-service 已确认的最大最终片段序号。
type AppendFinalTranscriptSegmentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// core-service 当前已持久化的最大最终片段序号。
	LastPersistedSequenceNo int64 `protobuf:"varint,1,opt,name=last_persisted_sequence_no,json=lastPersistedSequenceNo,proto3" json:"last_persisted_sequence_no,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AppendFinalTranscriptSegmentsResponse) Reset() {
	*x = AppendFinalTranscriptSegmentsResponse{}
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendFinalTranscriptSegmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendFinalTranscriptSegmentsResponse) ProtoMessage() {}

func (x *AppendFinalTranscriptSegmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendFinalTranscriptSegmentsResponse.ProtoReflect.Descriptor instead.
func (*AppendFinalTranscriptSegmentsResponse) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_internal_proto_rawDescGZIP(), []int{1}
}

func (x *AppendFinalTranscriptSegmentsResponse) GetLastPersistedSequenceNo() int64 {
	if x != nil {
		return x.LastPersistedSequenceNo
	}
	return 0
}

// ReportTranscriptionUsageRequest 是累计用量上报参数。
type ReportTranscriptionUsageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// core-service 会议 UUID。
	MeetingId string `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	// vision-service 转写会话 UUID。
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// core-service 额度预占 UUID。
	ReservationId string `protobuf:"bytes,3,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	// vision-service 已接受的唯一有效音频累计时长；只能单调递增。
	TotalAcceptedAudioDuration *durationpb.Duration `protobuf:"bytes,4,opt,name=total_accepted_audio_duration,json=totalAcceptedAudioDuration,proto3" json:"total_accepted_audio_duration,omitempty"`
	// vision-service 生成该累计值的时间。
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTranscriptionUsageRequest) Reset() {
	*x = ReportTranscriptionUsageRequest{}
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTranscriptionUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTranscriptionUsageRequest) ProtoMessage() {}

func (x *ReportTranscriptionUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTranscriptionUsageRequest.ProtoReflect.Descriptor instead.
func (*ReportTranscriptionUsageRequest) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_internal_proto_rawDescGZIP(), []int{2}
}

func (x *ReportTranscriptionUsageRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *ReportTranscriptionUsageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReportTranscriptionUsageRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReportTranscriptionUsageRequest) GetTotalAcceptedAudioDuration() *durationpb.Duration {
	if x != nil {
		return x.TotalAcceptedAudioDuration
	}
	return nil
}

func (x *ReportTranscriptionUsageRequest) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

// ReportTranscriptionUsageResponse 返回 core-service 接受的累计用量。
type ReportTranscriptionUsageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// core-service 当前记录的累计音频时长。
	RecordedAudioDuration *durationpb.Duration `protobuf:"bytes,1,opt,name=recorded_audio_duration,json=recordedAudioDuration,proto3" json:"recorded_audio_duration,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ReportTranscriptionUsageResponse) Reset() {
	*x = ReportTranscriptionUsageResponse{}
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTranscriptionUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTranscriptionUsageResponse) ProtoMessage() {}

func (x *ReportTranscriptionUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTranscriptionUsageResponse.ProtoReflect.Descriptor instead.
func (*ReportTranscriptionUsageResponse) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_internal_proto_rawDescGZIP(), []int{3}
}

func (x *ReportTranscriptionUsageResponse) GetRecordedAudioDuration() *durationpb.Duration {
	if x != nil {
		return x.RecordedAudioDuration
	}
	return nil
}

// CompleteTranscriptionRequest 是完成转写和结算预占的内部参数。
type CompleteTranscriptionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// core-service 会议 UUID。
	MeetingId string `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	// vision-service 转写会话 UUID。
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// core-service 额度预占 UUID。
	ReservationId string `protobuf:"bytes,3,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	// 最终累计接受的唯一有效音频时长。
	TotalAcceptedAudioDuration *durationpb.Duration `protobuf:"bytes,4,opt,name=total_accepted_audio_duration,json=totalAcceptedAudioDuration,proto3" json:"total_accepted_audio_duration,omitempty"`
	// Provider 返回的计费时长，仅用于成本审计。
	ProviderUsageDuration *durationpb.Duration `protobuf:"bytes,5,opt,name=provider_usage_duration,json=providerUsageDuration,proto3" json:"provider_usage_duration,omitempty"`
	// vision-service 完成转写的时间。
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTranscriptionRequest) Reset() {
	*x = CompleteTranscriptionRequest{}
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTranscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTranscriptionRequest) ProtoMessage() {}

func (x *CompleteTranscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTranscriptionRequest.ProtoReflect.Descriptor instead.
func (*CompleteTranscriptionRequest) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_internal_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteTranscriptionRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *CompleteTranscriptionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CompleteTranscriptionRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *CompleteTranscriptionRequest) GetTotalAcceptedAudioDuration() *durationpb.Duration {
	if x != nil {
		return x.TotalAcceptedAudioDuration
	}
	return nil
}

func (x *CompleteTranscriptionRequest) GetProviderUsageDuration() *durationpb.Duration {
	if x != nil {
		return x.ProviderUsageDuration
	}
	return nil
}

func (x *CompleteTranscriptionRequest) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// CompleteTranscriptionResponse 返回 core-service 最新转写状态。
type CompleteTranscriptionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 完成后的转写状态。
	Status TranscriptionStatus `protobuf:"varint,1,opt,name=status,proto3,enum=meeting.v1.TranscriptionStatus" json:"status,omitempty"`
	// 已最终结算到本月账本的音频时长。
	SettledAudioDuration *durationpb.Duration `protobuf:"bytes,2,opt,name=settled_audio_duration,json=settledAudioDuration,proto3" json:"settled_audio_duration,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CompleteTranscriptionResponse) Reset() {
	*x = CompleteTranscriptionResponse{}
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTranscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTranscriptionResponse) ProtoMessage() {}

func (x *CompleteTranscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTranscriptionResponse.ProtoReflect.Descriptor instead.
func (*CompleteTranscriptionResponse) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_internal_proto_rawDescGZIP(), []int{5}
}

func (x *CompleteTranscriptionResponse) GetStatus() TranscriptionStatus {
	if x != nil {
		return x.Status
	}
	return TranscriptionStatus_TRANSCRIPTION_STATUS_UNSPECIFIED
}

func (x *CompleteTranscriptionResponse) GetSettledAudioDuration() *durationpb.Duration {
	if x != nil {
		return x.SettledAudioDuration
	}
	return nil
}

// FailTranscriptionRequest 是记录失败和结算预占的内部参数。
type FailTranscriptionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// core-service 会议 UUID。
	MeetingId string `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	// vision-service 转写会话 UUID。
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// core-service 额度预占 UUID。
	ReservationId string `protobuf:"bytes,3,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	// 失败前累计接受的唯一有效音频时长。
	TotalAcceptedAudioDuration *durationpb.Duration `protobuf:"bytes,4,opt,name=total_accepted_audio_duration,json=totalAcceptedAudioDuration,proto3" json:"total_accepted_audio_duration,omitempty"`
	// 稳定失败分类；不得包含 Provider 原始错误文本。
	Reason TranscriptionFailureReason `protobuf:"varint,5,opt,name=reason,proto3,enum=meeting.v1.TranscriptionFailureReason" json:"reason,omitempty"`
	// vision-service 记录失败的时间。
	FailedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailTranscriptionRequest) Reset() {
	*x = FailTranscriptionRequest{}
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailTranscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailTranscriptionRequest) ProtoMessage() {}

func (x *FailTranscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailTranscriptionRequest.ProtoReflect.Descriptor instead.
func (*FailTranscriptionRequest) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_internal_proto_rawDescGZIP(), []int{6}
}

func (x *FailTranscriptionRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *FailTranscriptionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *FailTranscriptionRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *FailTranscriptionRequest) GetTotalAcceptedAudioDuration() *durationpb.Duration {
	if x != nil {
		return x.TotalAcceptedAudioDuration
	}
	return nil
}

func (x *FailTranscriptionRequest) GetReason() TranscriptionFailureReason {
	if x != nil {
		return x.Reason
	}
	return TranscriptionFailureReason_TRANSCRIPTION_FAILURE_REASON_UNSPECIFIED
}

func (x *FailTranscriptionRequest) GetFailedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FailedAt
	}
	return nil
}

// FailTranscriptionResponse 返回 core-service 最新转写状态。
type FailTranscriptionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 失败后的转写状态。
	Status TranscriptionStatus `protobuf:"varint,1,opt,name=status,proto3,enum=meeting.v1.TranscriptionStatus" json:"status,omitempty"`
	// 已最终结算到本月账本的音频时长。
	SettledAudioDuration *durationpb.Duration `protobuf:"bytes,2,opt,name=settled_audio_duration,json=settledAudioDuration,proto3" json:"settled_audio_duration,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FailTranscriptionResponse) Reset() {
	*x = FailTranscriptionResponse{}
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailTranscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailTranscriptionResponse) ProtoMessage() {}

func (x *FailTranscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailTranscriptionResponse.ProtoReflect.Descriptor instead.
func (*FailTranscriptionResponse) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_internal_proto_rawDescGZIP(), []int{7}
}

func (x *FailTranscriptionResponse) GetStatus() TranscriptionStatus {
	if x != nil {
		return x.Status
	}
	return TranscriptionStatus_TRANSCRIPTION_STATUS_UNSPECIFIED
}

func (x *FailTranscriptionResponse) GetSettledAudioDuration() *durationpb.Duration {
	if x != nil {
		return x.SettledAudioDuration
	}
	return nil
}

// GetMeetingTranscriptSnapshotRequest 查询一个已经冻结的最终转写版本。
type GetMeetingTranscriptSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// core-service 会议 UUID。
	MeetingId string `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	// 任务创建时记录的最终转写版本。
	TranscriptRevision int64 `protobuf:"varint,2,opt,name=transcript_revision,json=transcriptRevision,proto3" json:"transcript_revision,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetMeetingTranscriptSnapshotRequest) Reset() {
	*x = GetMeetingTranscriptSnapshotRequest{}
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetingTranscriptSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingTranscriptSnapshotRequest) ProtoMessage() {}

func (x *GetMeetingTranscriptSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingTranscriptSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetMeetingTranscriptSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_internal_proto_rawDescGZIP(), []int{8}
}

func (x *GetMeetingTranscriptSnapshotRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *GetMeetingTranscriptSnapshotRequest) GetTranscriptRevision() int64 {
	if x != nil {
		return x.TranscriptRevision
	}
	return 0
}

// GetMeetingTranscriptSnapshotResponse 返回有界的完整最终转写。
type GetMeetingTranscriptSnapshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 会议识别语言。
	Language MeetingLanguage `protobuf:"varint,1,opt,name=language,proto3,enum=meeting.v1.MeetingLanguage" json:"language,omitempty"`
	// 实际返回的转写版本。
	TranscriptRevision int64 `protobuf:"varint,2,opt,name=transcript_revision,json=transcriptRevision,proto3" json:"transcript_revision,omitempty"`
	// 按 sequence_no 升序排列的最终片段。
	Segments      []*TranscriptSegment `protobuf:"bytes,3,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeetingTranscriptSnapshotResponse) Reset() {
	*x = GetMeetingTranscriptSnapshotResponse{}
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetingTranscriptSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingTranscriptSnapshotResponse) ProtoMessage() {}

func (x *GetMeetingTranscriptSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingTranscriptSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetMeetingTranscriptSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_internal_proto_rawDescGZIP(), []int{9}
}

func (x *GetMeetingTranscriptSnapshotResponse) GetLanguage() MeetingLanguage {
	if x != nil {
		return x.Language
	}
	return MeetingLanguage_MEETING_LANGUAGE_UNSPECIFIED
}

func (x *GetMeetingTranscriptSnapshotResponse) GetTranscriptRevision() int64 {
	if x != nil {
		return x.TranscriptRevision
	}
	return 0
}

func (x *GetMeetingTranscriptSnapshotResponse) GetSegments() []*TranscriptSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

// CompleteMeetingSummaryRequest 是保存成功纪要的内部命令。
type CompleteMeetingSummaryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// core-service 会议 UUID。
	MeetingId string `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	// core-service 预先分配的纪要版本。
	Version int64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// 生成任务使用的最终转写版本。
	SourceTranscriptRevision int64 `protobuf:"varint,3,opt,name=source_transcript_revision,json=sourceTranscriptRevision,proto3" json:"source_transcript_revision,omitempty"`
	// 经过 vision 校验的结构化纪要。
	Summary       *MeetingSummary `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMeetingSummaryRequest) Reset() {
	*x = CompleteMeetingSummaryRequest{}
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMeetingSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMeetingSummaryRequest) ProtoMessage() {}

func (x *CompleteMeetingSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMeetingSummaryRequest.ProtoReflect.Descriptor instead.
func (*CompleteMeetingSummaryRequest) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_internal_proto_rawDescGZIP(), []int{10}
}

func (x *CompleteMeetingSummaryRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *CompleteMeetingSummaryRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CompleteMeetingSummaryRequest) GetSourceTranscriptRevision() int64 {
	if x != nil {
		return x.SourceTranscriptRevision
	}
	return 0
}

func (x *CompleteMeetingSummaryRequest) GetSummary() *MeetingSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

// CompleteMeetingSummaryResponse 返回 core 最新纪要状态。
type CompleteMeetingSummaryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 完成后的纪要状态。
	Status        MeetingSummaryStatus `protobuf:"varint,1,opt,name=status,proto3,enum=meeting.v1.MeetingSummaryStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMeetingSummaryResponse) Reset() {
	*x = CompleteMeetingSummaryResponse{}
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMeetingSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMeetingSummaryResponse) ProtoMessage() {}

func (x *CompleteMeetingSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMeetingSummaryResponse.ProtoReflect.Descriptor instead.
func (*CompleteMeetingSummaryResponse) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_internal_proto_rawDescGZIP(), []int{11}
}

func (x *CompleteMeetingSummaryResponse) GetStatus() MeetingSummaryStatus {
	if x != nil {
		return x.Status
	}
	return MeetingSummaryStatus_MEETING_SUMMARY_STATUS_UNSPECIFIED
}

// FailMeetingSummaryRequest 是记录纪要失败的内部命令。
type FailMeetingSummaryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// core-service 会议 UUID。
	MeetingId string `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	// core-service 预先分配的纪要版本。
	Version int64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// 生成任务使用的最终转写版本。
	SourceTranscriptRevision int64 `protobuf:"varint,3,opt,name=source_transcript_revision,json=sourceTranscriptRevision,proto3" json:"source_transcript_revision,omitempty"`
	// 稳定、脱敏的失败分类。
	Reason MeetingSummaryFailureReason `protobuf:"varint,4,opt,name=reason,proto3,enum=meeting.v1.MeetingSummaryFailureReason" json:"reason,omitempty"`
	// vision 确认失败的时间。
	FailedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailMeetingSummaryRequest) Reset() {
	*x = FailMeetingSummaryRequest{}
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailMeetingSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailMeetingSummaryRequest) ProtoMessage() {}

func (x *FailMeetingSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailMeetingSummaryRequest.ProtoReflect.Descriptor instead.
func (*FailMeetingSummaryRequest) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_internal_proto_rawDescGZIP(), []int{12}
}

func (x *FailMeetingSummaryRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *FailMeetingSummaryRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *FailMeetingSummaryRequest) GetSourceTranscriptRevision() int64 {
	if x != nil {
		return x.SourceTranscriptRevision
	}
	return 0
}

func (x *FailMeetingSummaryRequest) GetReason() MeetingSummaryFailureReason {
	if x != nil {
		return x.Reason
	}
	return MeetingSummaryFailureReason_MEETING_SUMMARY_FAILURE_REASON_UNSPECIFIED
}

func (x *FailMeetingSummaryRequest) GetFailedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FailedAt
	}
	return nil
}

// FailMeetingSummaryResponse 返回 core 最新纪要状态。
type FailMeetingSummaryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 失败后的纪要状态。
	Status        MeetingSummaryStatus `protobuf:"varint,1,opt,name=status,proto3,enum=meeting.v1.MeetingSummaryStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailMeetingSummaryResponse) Reset() {
	*x = FailMeetingSummaryResponse{}
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailMeetingSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailMeetingSummaryResponse) ProtoMessage() {}

func (x *FailMeetingSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_v1_meeting_internal_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailMeetingSummaryResponse.ProtoReflect.Descriptor instead.
func (*FailMeetingSummaryResponse) Descriptor() ([]byte, []int) {
	return file_meeting_v1_meeting_internal_proto_rawDescGZIP(), []int{13}
}

func (x *FailMeetingSummaryResponse) GetStatus() MeetingSummaryStatus {
	if x != nil {
		return x.Status
	}
	return MeetingSummaryStatus_MEETING_SUMMARY_STATUS_UNSPECIFIED
}

var File_meeting_v1_meeting_internal_proto protoreflect.FileDescriptor

const file_meeting_v1_meeting_internal_proto_rawDesc = "" +
	"\n" +
	"!meeting/v1/meeting_internal.proto\x12\n" +
	"meeting.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18meeting/v1/meeting.proto\"\xce\x01\n" +
	"$AppendFinalTranscriptSegmentsRequest\x12\"\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tmeetingId\x12\"\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tB\x03\xe0A\x02R\tsessionId\x12\x1e\n" +
	"\bbatch_id\x18\x03 \x01(\tB\x03\xe0A\x02R\abatchId\x12>\n" +
	"\bsegments\x18\x04 \x03(\v2\x1d.meeting.v1.TranscriptSegmentB\x03\xe0A\x02R\bsegments\"d\n" +
	"%AppendFinalTranscriptSegmentsResponse\x12;\n" +
	"\x1alast_persisted_sequence_no\x18\x01 \x01(\x03R\x17lastPersistedSequenceNo\"\xba\x02\n" +
	"\x1fReportTranscriptionUsageRequest\x12\"\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tmeetingId\x12\"\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tB\x03\xe0A\x02R\tsessionId\x12*\n" +
	"\x0ereservation_id\x18\x03 \x01(\tB\x03\xe0A\x02R\rreservationId\x12a\n" +
	"\x1dtotal_accepted_audio_duration\x18\x04 \x01(\v2\x19.google.protobuf.DurationB\x03\xe0A\x02R\x1atotalAcceptedAudioDuration\x12@\n" +
	"\vobserved_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x02R\n" +
	"observedAt\"u\n" +
	" ReportTranscriptionUsageResponse\x12Q\n" +
	"\x17recorded_audio_duration\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x15recordedAudioDuration\"\x8c\x03\n" +
	"\x1cCompleteTranscriptionRequest\x12\"\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tmeetingId\x12\"\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tB\x03\xe0A\x02R\tsessionId\x12*\n" +
	"\x0ereservation_id\x18\x03 \x01(\tB\x03\xe0A\x02R\rreservationId\x12a\n" +
	"\x1dtotal_accepted_audio_duration\x18\x04 \x01(\v2\x19.google.protobuf.DurationB\x03\xe0A\x02R\x1atotalAcceptedAudioDuration\x12Q\n" +
	"\x17provider_usage_duration\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x15providerUsageDuration\x12B\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x02R\vcompletedAt\"\xa9\x01\n" +
	"\x1dCompleteTranscriptionResponse\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.meeting.v1.TranscriptionStatusR\x06status\x12O\n" +
	"\x16settled_audio_duration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x14settledAudioDuration\"\xf4\x02\n" +
	"\x18FailTranscriptionRequest\x12\"\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tmeetingId\x12\"\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tB\x03\xe0A\x02R\tsessionId\x12*\n" +
	"\x0ereservation_id\x18\x03 \x01(\tB\x03\xe0A\x02R\rreservationId\x12a\n" +
	"\x1dtotal_accepted_audio_duration\x18\x04 \x01(\v2\x19.google.protobuf.DurationB\x03\xe0A\x02R\x1atotalAcceptedAudioDuration\x12C\n" +
	"\x06reason\x18\x05 \x01(\x0e2&.meeting.v1.TranscriptionFailureReasonB\x03\xe0A\x02R\x06reason\x12<\n" +
	"\tfailed_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x02R\bfailedAt\"\xa5\x01\n" +
	"\x19FailTranscriptionResponse\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.meeting.v1.TranscriptionStatusR\x06status\x12O\n" +
	"\x16settled_audio_duration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x14settledAudioDuration\"\x7f\n" +
	"#GetMeetingTranscriptSnapshotRequest\x12\"\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tmeetingId\x124\n" +
	"\x13transcript_revision\x18\x02 \x01(\x03B\x03\xe0A\x02R\x12transcriptRevision\"\xcb\x01\n" +
	"$GetMeetingTranscriptSnapshotResponse\x127\n" +
	"\blanguage\x18\x01 \x01(\x0e2\x1b.meeting.v1.MeetingLanguageR\blanguage\x12/\n" +
	"\x13transcript_revision\x18\x02 \x01(\x03R\x12transcriptRevision\x129\n" +
	"\bsegments\x18\x03 \x03(\v2\x1d.meeting.v1.TranscriptSegmentR\bsegments\"\xe0\x01\n" +
	"\x1dCompleteMeetingSummaryRequest\x12\"\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tmeetingId\x12\x1d\n" +
	"\aversion\x18\x02 \x01(\x03B\x03\xe0A\x02R\aversion\x12A\n" +
	"\x1asource_transcript_revision\x18\x03 \x01(\x03B\x03\xe0A\x02R\x18sourceTranscriptRevision\x129\n" +
	"\asummary\x18\x04 \x01(\v2\x1a.meeting.v1.MeetingSummaryB\x03\xe0A\x02R\asummary\"Z\n" +
	"\x1eCompleteMeetingSummaryResponse\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2 .meeting.v1.MeetingSummaryStatusR\x06status\"\xa5\x02\n" +
	"\x19FailMeetingSummaryRequest\x12\"\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tmeetingId\x12\x1d\n" +
	"\aversion\x18\x02 \x01(\x03B\x03\xe0A\x02R\aversion\x12A\n" +
	"\x1asource_transcript_revision\x18\x03 \x01(\x03B\x03\xe0A\x02R\x18sourceTranscriptRevision\x12D\n" +
	"\x06reason\x18\x04 \x01(\x0e2'.meeting.v1.MeetingSummaryFailureReasonB\x03\xe0A\x02R\x06reason\x12<\n" +
	"\tfailed_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x02R\bfailedAt\"V\n" +
	"\x1aFailMeetingSummaryResponse\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2 .meeting.v1.MeetingSummaryStatusR\x06status*\xff\x02\n" +
	"\x1bMeetingSummaryFailureReason\x12.\n" +
	"*MEETING_SUMMARY_FAILURE_REASON_UNSPECIFIED\x10\x00\x127\n" +
	"3MEETING_SUMMARY_FAILURE_REASON_PROVIDER_UNAVAILABLE\x10\x01\x124\n" +
	"0MEETING_SUMMARY_FAILURE_REASON_PROVIDER_REJECTED\x10\x02\x121\n" +
	"-MEETING_SUMMARY_FAILURE_REASON_OUTPUT_INVALID\x10\x03\x125\n" +
	"1MEETING_SUMMARY_FAILURE_REASON_TRANSCRIPT_INVALID\x10\x04\x12*\n" +
	"&MEETING_SUMMARY_FAILURE_REASON_TIMEOUT\x10\x05\x12+\n" +
	"'MEETING_SUMMARY_FAILURE_REASON_INTERNAL\x10\x06*\x98\x03\n" +
	"\x1aTranscriptionFailureReason\x12,\n" +
	"(TRANSCRIPTION_FAILURE_REASON_UNSPECIFIED\x10\x00\x125\n" +
	"1TRANSCRIPTION_FAILURE_REASON_PROVIDER_UNAVAILABLE\x10\x01\x122\n" +
	".TRANSCRIPTION_FAILURE_REASON_PROVIDER_REJECTED\x10\x02\x12.\n" +
	"*TRANSCRIPTION_FAILURE_REASON_AUDIO_INVALID\x10\x03\x12(\n" +
	"$TRANSCRIPTION_FAILURE_REASON_TIMEOUT\x10\x04\x120\n" +
	",TRANSCRIPTION_FAILURE_REASON_QUOTA_EXHAUSTED\x10\x05\x12*\n" +
	"&TRANSCRIPTION_FAILURE_REASON_CANCELLED\x10\x06\x12)\n" +
	"%TRANSCRIPTION_FAILURE_REASON_INTERNAL\x10\a2\xc6\x06\n" +
	"\x1cMeetingIngestInternalService\x12\x84\x01\n" +
	"\x1dAppendFinalTranscriptSegments\x120.meeting.v1.AppendFinalTranscriptSegmentsRequest\x1a1.meeting.v1.AppendFinalTranscriptSegmentsResponse\x12u\n" +
	"\x18ReportTranscriptionUsage\x12+.meeting.v1.ReportTranscriptionUsageRequest\x1a,.meeting.v1.ReportTranscriptionUsageResponse\x12l\n" +
	"\x15CompleteTranscription\x12(.meeting.v1.CompleteTranscriptionRequest\x1a).meeting.v1.CompleteTranscriptionResponse\x12`\n" +
	"\x11FailTranscription\x12$.meeting.v1.FailTranscriptionRequest\x1a%.meeting.v1.FailTranscriptionResponse\x12\x81\x01\n" +
	"\x1cGetMeetingTranscriptSnapshot\x12/.meeting.v1.GetMeetingTranscriptSnapshotRequest\x1a0.meeting.v1.GetMeetingTranscriptSnapshotResponse\x12o\n" +
	"\x16CompleteMeetingSummary\x12).meeting.v1.CompleteMeetingSummaryRequest\x1a*.meeting.v1.CompleteMeetingSummaryResponse\x12c\n" +
	"\x12FailMeetingSummary\x12%.meeting.v1.FailMeetingSummaryRequest\x1a&.meeting.v1.FailMeetingSummaryResponseB<Z:github.com/tiehu-ai/tiehu-fitness/api/meeting/v1;meetingv1b\x06proto3"

var (
	file_meeting_v1_meeting_internal_proto_rawDescOnce sync.Once
	file_meeting_v1_meeting_internal_proto_rawDescData []byte
)

func file_meeting_v1_meeting_internal_proto_rawDescGZIP() []byte {
	file_meeting_v1_meeting_internal_proto_rawDescOnce.Do(func() {
		file_meeting_v1_meeting_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meeting_v1_meeting_internal_proto_rawDesc), len(file_meeting_v1_meeting_internal_proto_rawDesc)))
	})
	return file_meeting_v1_meeting_internal_proto_rawDescData
}

var file_meeting_v1_meeting_internal_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_meeting_v1_meeting_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_meeting_v1_meeting_internal_proto_goTypes = []any{
	(MeetingSummaryFailureReason)(0),              // 0: meeting.v1.MeetingSummaryFailureReason
	(TranscriptionFailureReason)(0),               // 1: meeting.v1.TranscriptionFailureReason
	(*AppendFinalTranscriptSegmentsRequest)(nil),  // 2: meeting.v1.AppendFinalTranscriptSegmentsRequest
	(*AppendFinalTranscriptSegmentsResponse)(nil), // 3: meeting.v1.AppendFinalTranscriptSegmentsResponse
	(*ReportTranscriptionUsageRequest)(nil),       // 4: meeting.v1.ReportTranscriptionUsageRequest
	(*ReportTranscriptionUsageResponse)(nil),      // 5: meeting.v1.ReportTranscriptionUsageResponse
	(*CompleteTranscriptionRequest)(nil),          // 6: meeting.v1.CompleteTranscriptionRequest
	(*CompleteTranscriptionResponse)(nil),         // 7: meeting.v1.CompleteTranscriptionResponse
	(*FailTranscriptionRequest)(nil),              // 8: meeting.v1.FailTranscriptionRequest
	(*FailTranscriptionResponse)(nil),             // 9: meeting.v1.FailTranscriptionResponse
	(*GetMeetingTranscriptSnapshotRequest)(nil),   // 10: meeting.v1.GetMeetingTranscriptSnapshotRequest
	(*GetMeetingTranscriptSnapshotResponse)(nil),  // 11: meeting.v1.GetMeetingTranscriptSnapshotResponse
	(*CompleteMeetingSummaryRequest)(nil),         // 12: meeting.v1.CompleteMeetingSummaryRequest
	(*CompleteMeetingSummaryResponse)(nil),        // 13: meeting.v1.CompleteMeetingSummaryResponse
	(*FailMeetingSummaryRequest)(nil),             // 14: meeting.v1.FailMeetingSummaryRequest
	(*FailMeetingSummaryResponse)(nil),            // 15: meeting.v1.FailMeetingSummaryResponse
	(*TranscriptSegment)(nil),                     // 16: meeting.v1.TranscriptSegment
	(*durationpb.Duration)(nil),                   // 17: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),                 // 18: google.protobuf.Timestamp
	(TranscriptionStatus)(0),                      // 19: meeting.v1.TranscriptionStatus
	(MeetingLanguage)(0),                          // 20: meeting.v1.MeetingLanguage
	(*MeetingSummary)(nil),                        // 21: meeting.v1.MeetingSummary
	(MeetingSummaryStatus)(0),                     // 22: meeting.v1.MeetingSummaryStatus
}
var file_meeting_v1_meeting_internal_proto_depIdxs = []int32{
	16, // 0: meeting.v1.AppendFinalTranscriptSegmentsRequest.segments:type_name -> meeting.v1.TranscriptSegment
	17, // 1: meeting.v1.ReportTranscriptionUsageRequest.total_accepted_audio_duration:type_name -> google.protobuf.Duration
	18, // 2: meeting.v1.ReportTranscriptionUsageRequest.observed_at:type_name -> google.protobuf.Timestamp
	17, // 3: meeting.v1.ReportTranscriptionUsageResponse.recorded_audio_duration:type_name -> google.protobuf.Duration
	17, // 4: meeting.v1.CompleteTranscriptionRequest.total_accepted_audio_duration:type_name -> google.protobuf.Duration
	17, // 5: meeting.v1.CompleteTranscriptionRequest.provider_usage_duration:type_name -> google.protobuf.Duration
	18, // 6: meeting.v1.CompleteTranscriptionRequest.completed_at:type_name -> google.protobuf.Timestamp
	19, // 7: meeting.v1.CompleteTranscriptionResponse.status:type_name -> meeting.v1.TranscriptionStatus
	17, // 8: meeting.v1.CompleteTranscriptionResponse.settled_audio_duration:type_name -> google.protobuf.Duration
	17, // 9: meeting.v1.FailTranscriptionRequest.total_accepted_audio_duration:type_name -> google.protobuf.Duration
	1,  // 10: meeting.v1.FailTranscriptionRequest.reason:type_name -> meeting.v1.TranscriptionFailureReason
	18, // 11: meeting.v1.FailTranscriptionRequest.failed_at:type_name -> google.protobuf.Timestamp
	19, // 12: meeting.v1.FailTranscriptionResponse.status:type_name -> meeting.v1.TranscriptionStatus
	17, // 13: meeting.v1.FailTranscriptionResponse.settled_audio_duration:type_name -> google.protobuf.Duration
	20, // 14: meeting.v1.GetMeetingTranscriptSnapshotResponse.language:type_name -> meeting.v1.MeetingLanguage
	16, // 15: meeting.v1.GetMeetingTranscriptSnapshotResponse.segments:type_name -> meeting.v1.TranscriptSegment
	21, // 16: meeting.v1.CompleteMeetingSummaryRequest.summary:type_name -> meeting.v1.MeetingSummary
	22, // 17: meeting.v1.CompleteMeetingSummaryResponse.status:type_name -> meeting.v1.MeetingSummaryStatus
	0,  // 18: meeting.v1.FailMeetingSummaryRequest.reason:type_name -> meeting.v1.MeetingSummaryFailureReason
	18, // 19: meeting.v1.FailMeetingSummaryRequest.failed_at:type_name -> google.protobuf.Timestamp
	22, // 20: meeting.v1.FailMeetingSummaryResponse.status:type_name -> meeting.v1.MeetingSummaryStatus
	2,  // 21: meeting.v1.MeetingIngestInternalService.AppendFinalTranscriptSegments:input_type -> meeting.v1.AppendFinalTranscriptSegmentsRequest
	4,  // 22: meeting.v1.MeetingIngestInternalService.ReportTranscriptionUsage:input_type -> meeting.v1.ReportTranscriptionUsageRequest
	6,  // 23: meeting.v1.MeetingIngestInternalService.CompleteTranscription:input_type -> meeting.v1.CompleteTranscriptionRequest
	8,  // 24: meeting.v1.MeetingIngestInternalService.FailTranscription:input_type -> meeting.v1.FailTranscriptionRequest
	10, // 25: meeting.v1.MeetingIngestInternalService.GetMeetingTranscriptSnapshot:input_type -> meeting.v1.GetMeetingTranscriptSnapshotRequest
	12, // 26: meeting.v1.MeetingIngestInternalService.CompleteMeetingSummary:input_type -> meeting.v1.CompleteMeetingSummaryRequest
	14, // 27: meeting.v1.MeetingIngestInternalService.FailMeetingSummary:input_type -> meeting.v1.FailMeetingSummaryRequest
	3,  // 28: meeting.v1.MeetingIngestInternalService.AppendFinalTranscriptSegments:output_type -> meeting.v1.AppendFinalTranscriptSegmentsResponse
	5,  // 29: meeting.v1.MeetingIngestInternalService.ReportTranscriptionUsage:output_type -> meeting.v1.ReportTranscriptionUsageResponse
	7,  // 30: meeting.v1.MeetingIngestInternalService.CompleteTranscription:output_type -> meeting.v1.CompleteTranscriptionResponse
	9,  // 31: meeting.v1.MeetingIngestInternalService.FailTranscription:output_type -> meeting.v1.FailTranscriptionResponse
	11, // 32: meeting.v1.MeetingIngestInternalService.GetMeetingTranscriptSnapshot:output_type -> meeting.v1.GetMeetingTranscriptSnapshotResponse
	13, // 33: meeting.v1.MeetingIngestInternalService.CompleteMeetingSummary:output_type -> meeting.v1.CompleteMeetingSummaryResponse
	15, // 34: meeting.v1.MeetingIngestInternalService.FailMeetingSummary:output_type -> meeting.v1.FailMeetingSummaryResponse
	28, // [28:35] is the sub-list for method output_type
	21, // [21:28] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_meeting_v1_meeting_internal_proto_init() }
func file_meeting_v1_meeting_internal_proto_init() {
	if File_meeting_v1_meeting_internal_proto != nil {
		return
	}
	file_meeting_v1_meeting_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meeting_v1_meeting_internal_proto_rawDesc), len(file_meeting_v1_meeting_internal_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meeting_v1_meeting_internal_proto_goTypes,
		DependencyIndexes: file_meeting_v1_meeting_internal_proto_depIdxs,
		EnumInfos:         file_meeting_v1_meeting_internal_proto_enumTypes,
		MessageInfos:      file_meeting_v1_meeting_internal_proto_msgTypes,
	}.Build()
	File_meeting_v1_meeting_internal_proto = out.File
	file_meeting_v1_meeting_internal_proto_goTypes = nil
	file_meeting_v1_meeting_internal_proto_depIdxs = nil
}
