// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: vision/v1/transcription_internal.proto

package visionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MeetingTranscriptionInternalService_PrepareTranscription_FullMethodName   = "/vision.v1.MeetingTranscriptionInternalService/PrepareTranscription"
	MeetingTranscriptionInternalService_CancelTranscription_FullMethodName    = "/vision.v1.MeetingTranscriptionInternalService/CancelTranscription"
	MeetingTranscriptionInternalService_GetTranscriptionStatus_FullMethodName = "/vision.v1.MeetingTranscriptionInternalService/GetTranscriptionStatus"
	MeetingTranscriptionInternalService_PrepareMeetingSummary_FullMethodName  = "/vision.v1.MeetingTranscriptionInternalService/PrepareMeetingSummary"
)

// MeetingTranscriptionInternalServiceClient is the client API for MeetingTranscriptionInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MeetingTranscriptionInternalService 提供 core-service 到 vision-service 的内部转写控制能力。
type MeetingTranscriptionInternalServiceClient interface {
	// PrepareTranscription 幂等准备实时转写会话并签发一次性 ticket。
	PrepareTranscription(ctx context.Context, in *PrepareTranscriptionRequest, opts ...grpc.CallOption) (*PrepareTranscriptionResponse, error)
	// CancelTranscription 幂等取消尚未正常结束的实时转写会话。
	CancelTranscription(ctx context.Context, in *CancelTranscriptionRequest, opts ...grpc.CallOption) (*CancelTranscriptionResponse, error)
	// GetTranscriptionStatus 查询 vision-service 拥有的转写 session 状态。
	GetTranscriptionStatus(ctx context.Context, in *GetTranscriptionStatusRequest, opts ...grpc.CallOption) (*GetTranscriptionStatusResponse, error)
	// PrepareMeetingSummary 幂等创建一个异步会议纪要任务。
	PrepareMeetingSummary(ctx context.Context, in *PrepareMeetingSummaryRequest, opts ...grpc.CallOption) (*PrepareMeetingSummaryResponse, error)
}

type meetingTranscriptionInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeetingTranscriptionInternalServiceClient(cc grpc.ClientConnInterface) MeetingTranscriptionInternalServiceClient {
	return &meetingTranscriptionInternalServiceClient{cc}
}

func (c *meetingTranscriptionInternalServiceClient) PrepareTranscription(ctx context.Context, in *PrepareTranscriptionRequest, opts ...grpc.CallOption) (*PrepareTranscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareTranscriptionResponse)
	err := c.cc.Invoke(ctx, MeetingTranscriptionInternalService_PrepareTranscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingTranscriptionInternalServiceClient) CancelTranscription(ctx context.Context, in *CancelTranscriptionRequest, opts ...grpc.CallOption) (*CancelTranscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTranscriptionResponse)
	err := c.cc.Invoke(ctx, MeetingTranscriptionInternalService_CancelTranscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingTranscriptionInternalServiceClient) GetTranscriptionStatus(ctx context.Context, in *GetTranscriptionStatusRequest, opts ...grpc.CallOption) (*GetTranscriptionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTranscriptionStatusResponse)
	err := c.cc.Invoke(ctx, MeetingTranscriptionInternalService_GetTranscriptionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingTranscriptionInternalServiceClient) PrepareMeetingSummary(ctx context.Context, in *PrepareMeetingSummaryRequest, opts ...grpc.CallOption) (*PrepareMeetingSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareMeetingSummaryResponse)
	err := c.cc.Invoke(ctx, MeetingTranscriptionInternalService_PrepareMeetingSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeetingTranscriptionInternalServiceServer is the server API for MeetingTranscriptionInternalService service.
// All implementations must embed UnimplementedMeetingTranscriptionInternalServiceServer
// for forward compatibility.
//
// MeetingTranscriptionInternalService 提供 core-service 到 vision-service 的内部转写控制能力。
type MeetingTranscriptionInternalServiceServer interface {
	// PrepareTranscription 幂等准备实时转写会话并签发一次性 ticket。
	PrepareTranscription(context.Context, *PrepareTranscriptionRequest) (*PrepareTranscriptionResponse, error)
	// CancelTranscription 幂等取消尚未正常结束的实时转写会话。
	CancelTranscription(context.Context, *CancelTranscriptionRequest) (*CancelTranscriptionResponse, error)
	// GetTranscriptionStatus 查询 vision-service 拥有的转写 session 状态。
	GetTranscriptionStatus(context.Context, *GetTranscriptionStatusRequest) (*GetTranscriptionStatusResponse, error)
	// PrepareMeetingSummary 幂等创建一个异步会议纪要任务。
	PrepareMeetingSummary(context.Context, *PrepareMeetingSummaryRequest) (*PrepareMeetingSummaryResponse, error)
	mustEmbedUnimplementedMeetingTranscriptionInternalServiceServer()
}

// UnimplementedMeetingTranscriptionInternalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeetingTranscriptionInternalServiceServer struct{}

func (UnimplementedMeetingTranscriptionInternalServiceServer) PrepareTranscription(context.Context, *PrepareTranscriptionRequest) (*PrepareTranscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareTranscription not implemented")
}
func (UnimplementedMeetingTranscriptionInternalServiceServer) CancelTranscription(context.Context, *CancelTranscriptionRequest) (*CancelTranscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTranscription not implemented")
}
func (UnimplementedMeetingTranscriptionInternalServiceServer) GetTranscriptionStatus(context.Context, *GetTranscriptionStatusRequest) (*GetTranscriptionStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTranscriptionStatus not implemented")
}
func (UnimplementedMeetingTranscriptionInternalServiceServer) PrepareMeetingSummary(context.Context, *PrepareMeetingSummaryRequest) (*PrepareMeetingSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareMeetingSummary not implemented")
}
func (UnimplementedMeetingTranscriptionInternalServiceServer) mustEmbedUnimplementedMeetingTranscriptionInternalServiceServer() {
}
func (UnimplementedMeetingTranscriptionInternalServiceServer) testEmbeddedByValue() {}

// UnsafeMeetingTranscriptionInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeetingTranscriptionInternalServiceServer will
// result in compilation errors.
type UnsafeMeetingTranscriptionInternalServiceServer interface {
	mustEmbedUnimplementedMeetingTranscriptionInternalServiceServer()
}

func RegisterMeetingTranscriptionInternalServiceServer(s grpc.ServiceRegistrar, srv MeetingTranscriptionInternalServiceServer) {
	// If the following call panics, it indicates UnimplementedMeetingTranscriptionInternalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MeetingTranscriptionInternalService_ServiceDesc, srv)
}

func _MeetingTranscriptionInternalService_PrepareTranscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareTranscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingTranscriptionInternalServiceServer).PrepareTranscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingTranscriptionInternalService_PrepareTranscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingTranscriptionInternalServiceServer).PrepareTranscription(ctx, req.(*PrepareTranscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingTranscriptionInternalService_CancelTranscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTranscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingTranscriptionInternalServiceServer).CancelTranscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingTranscriptionInternalService_CancelTranscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingTranscriptionInternalServiceServer).CancelTranscription(ctx, req.(*CancelTranscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingTranscriptionInternalService_GetTranscriptionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTranscriptionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingTranscriptionInternalServiceServer).GetTranscriptionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingTranscriptionInternalService_GetTranscriptionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingTranscriptionInternalServiceServer).GetTranscriptionStatus(ctx, req.(*GetTranscriptionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetingTranscriptionInternalService_PrepareMeetingSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareMeetingSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingTranscriptionInternalServiceServer).PrepareMeetingSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetingTranscriptionInternalService_PrepareMeetingSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingTranscriptionInternalServiceServer).PrepareMeetingSummary(ctx, req.(*PrepareMeetingSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MeetingTranscriptionInternalService_ServiceDesc is the grpc.ServiceDesc for MeetingTranscriptionInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeetingTranscriptionInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vision.v1.MeetingTranscriptionInternalService",
	HandlerType: (*MeetingTranscriptionInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrepareTranscription",
			Handler:    _MeetingTranscriptionInternalService_PrepareTranscription_Handler,
		},
		{
			MethodName: "CancelTranscription",
			Handler:    _MeetingTranscriptionInternalService_CancelTranscription_Handler,
		},
		{
			MethodName: "GetTranscriptionStatus",
			Handler:    _MeetingTranscriptionInternalService_GetTranscriptionStatus_Handler,
		},
		{
			MethodName: "PrepareMeetingSummary",
			Handler:    _MeetingTranscriptionInternalService_PrepareMeetingSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vision/v1/transcription_internal.proto",
}
