// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: vision/v1/vision.proto

package visionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VisionService_RecognizeEquipment_FullMethodName = "/vision.v1.VisionService/RecognizeEquipment"
	VisionService_AnalyzePosture_FullMethodName     = "/vision.v1.VisionService/AnalyzePosture"
	VisionService_GetAnalysisJob_FullMethodName     = "/vision.v1.VisionService/GetAnalysisJob"
)

// VisionServiceClient is the client API for VisionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VisionService 提供图片器材识别和视频姿势分析任务能力。
type VisionServiceClient interface {
	// RecognizeEquipment 创建图片器材识别任务。
	RecognizeEquipment(ctx context.Context, in *RecognizeEquipmentRequest, opts ...grpc.CallOption) (*RecognizeEquipmentResponse, error)
	// AnalyzePosture 创建视频姿势分析任务。
	AnalyzePosture(ctx context.Context, in *AnalyzePostureRequest, opts ...grpc.CallOption) (*AnalyzePostureResponse, error)
	// GetAnalysisJob 查询异步分析任务的状态和结果。
	GetAnalysisJob(ctx context.Context, in *GetAnalysisJobRequest, opts ...grpc.CallOption) (*GetAnalysisJobResponse, error)
}

type visionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVisionServiceClient(cc grpc.ClientConnInterface) VisionServiceClient {
	return &visionServiceClient{cc}
}

func (c *visionServiceClient) RecognizeEquipment(ctx context.Context, in *RecognizeEquipmentRequest, opts ...grpc.CallOption) (*RecognizeEquipmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecognizeEquipmentResponse)
	err := c.cc.Invoke(ctx, VisionService_RecognizeEquipment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visionServiceClient) AnalyzePosture(ctx context.Context, in *AnalyzePostureRequest, opts ...grpc.CallOption) (*AnalyzePostureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzePostureResponse)
	err := c.cc.Invoke(ctx, VisionService_AnalyzePosture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visionServiceClient) GetAnalysisJob(ctx context.Context, in *GetAnalysisJobRequest, opts ...grpc.CallOption) (*GetAnalysisJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnalysisJobResponse)
	err := c.cc.Invoke(ctx, VisionService_GetAnalysisJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VisionServiceServer is the server API for VisionService service.
// All implementations must embed UnimplementedVisionServiceServer
// for forward compatibility.
//
// VisionService 提供图片器材识别和视频姿势分析任务能力。
type VisionServiceServer interface {
	// RecognizeEquipment 创建图片器材识别任务。
	RecognizeEquipment(context.Context, *RecognizeEquipmentRequest) (*RecognizeEquipmentResponse, error)
	// AnalyzePosture 创建视频姿势分析任务。
	AnalyzePosture(context.Context, *AnalyzePostureRequest) (*AnalyzePostureResponse, error)
	// GetAnalysisJob 查询异步分析任务的状态和结果。
	GetAnalysisJob(context.Context, *GetAnalysisJobRequest) (*GetAnalysisJobResponse, error)
	mustEmbedUnimplementedVisionServiceServer()
}

// UnimplementedVisionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVisionServiceServer struct{}

func (UnimplementedVisionServiceServer) RecognizeEquipment(context.Context, *RecognizeEquipmentRequest) (*RecognizeEquipmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecognizeEquipment not implemented")
}
func (UnimplementedVisionServiceServer) AnalyzePosture(context.Context, *AnalyzePostureRequest) (*AnalyzePostureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzePosture not implemented")
}
func (UnimplementedVisionServiceServer) GetAnalysisJob(context.Context, *GetAnalysisJobRequest) (*GetAnalysisJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnalysisJob not implemented")
}
func (UnimplementedVisionServiceServer) mustEmbedUnimplementedVisionServiceServer() {}
func (UnimplementedVisionServiceServer) testEmbeddedByValue()                       {}

// UnsafeVisionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VisionServiceServer will
// result in compilation errors.
type UnsafeVisionServiceServer interface {
	mustEmbedUnimplementedVisionServiceServer()
}

func RegisterVisionServiceServer(s grpc.ServiceRegistrar, srv VisionServiceServer) {
	// If the following call panics, it indicates UnimplementedVisionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VisionService_ServiceDesc, srv)
}

func _VisionService_RecognizeEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecognizeEquipmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisionServiceServer).RecognizeEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisionService_RecognizeEquipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisionServiceServer).RecognizeEquipment(ctx, req.(*RecognizeEquipmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisionService_AnalyzePosture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzePostureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisionServiceServer).AnalyzePosture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisionService_AnalyzePosture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisionServiceServer).AnalyzePosture(ctx, req.(*AnalyzePostureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisionService_GetAnalysisJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnalysisJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisionServiceServer).GetAnalysisJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisionService_GetAnalysisJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisionServiceServer).GetAnalysisJob(ctx, req.(*GetAnalysisJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VisionService_ServiceDesc is the grpc.ServiceDesc for VisionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VisionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vision.v1.VisionService",
	HandlerType: (*VisionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecognizeEquipment",
			Handler:    _VisionService_RecognizeEquipment_Handler,
		},
		{
			MethodName: "AnalyzePosture",
			Handler:    _VisionService_AnalyzePosture_Handler,
		},
		{
			MethodName: "GetAnalysisJob",
			Handler:    _VisionService_GetAnalysisJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vision/v1/vision.proto",
}
