// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: vision/v1/vision.proto

package visionv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationVisionServiceAnalyzePosture = "/vision.v1.VisionService/AnalyzePosture"
const OperationVisionServiceGetAnalysisJob = "/vision.v1.VisionService/GetAnalysisJob"
const OperationVisionServiceRecognizeEquipment = "/vision.v1.VisionService/RecognizeEquipment"

type VisionServiceHTTPServer interface {
	AnalyzePosture(context.Context, *AnalyzePostureRequest) (*AnalyzePostureResponse, error)
	GetAnalysisJob(context.Context, *GetAnalysisJobRequest) (*GetAnalysisJobResponse, error)
	RecognizeEquipment(context.Context, *RecognizeEquipmentRequest) (*RecognizeEquipmentResponse, error)
}

func RegisterVisionServiceHTTPServer(s *http.Server, srv VisionServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/vision/equipment:recognize", _VisionService_RecognizeEquipment0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/vision/posture:analyze", _VisionService_AnalyzePosture0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/vision/jobs/{job_id}", _VisionService_GetAnalysisJob0_HTTP_Handler(srv))
}

func _VisionService_RecognizeEquipment0_HTTP_Handler(srv VisionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RecognizeEquipmentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVisionServiceRecognizeEquipment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RecognizeEquipment(ctx, req.(*RecognizeEquipmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RecognizeEquipmentResponse)
		return ctx.Result(200, reply)
	}
}

func _VisionService_AnalyzePosture0_HTTP_Handler(srv VisionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AnalyzePostureRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVisionServiceAnalyzePosture)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AnalyzePosture(ctx, req.(*AnalyzePostureRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AnalyzePostureResponse)
		return ctx.Result(200, reply)
	}
}

func _VisionService_GetAnalysisJob0_HTTP_Handler(srv VisionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAnalysisJobRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVisionServiceGetAnalysisJob)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAnalysisJob(ctx, req.(*GetAnalysisJobRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAnalysisJobResponse)
		return ctx.Result(200, reply)
	}
}

type VisionServiceHTTPClient interface {
	AnalyzePosture(ctx context.Context, req *AnalyzePostureRequest, opts ...http.CallOption) (rsp *AnalyzePostureResponse, err error)
	GetAnalysisJob(ctx context.Context, req *GetAnalysisJobRequest, opts ...http.CallOption) (rsp *GetAnalysisJobResponse, err error)
	RecognizeEquipment(ctx context.Context, req *RecognizeEquipmentRequest, opts ...http.CallOption) (rsp *RecognizeEquipmentResponse, err error)
}

type VisionServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewVisionServiceHTTPClient(client *http.Client) VisionServiceHTTPClient {
	return &VisionServiceHTTPClientImpl{client}
}

func (c *VisionServiceHTTPClientImpl) AnalyzePosture(ctx context.Context, in *AnalyzePostureRequest, opts ...http.CallOption) (*AnalyzePostureResponse, error) {
	var out AnalyzePostureResponse
	pattern := "/v1/vision/posture:analyze"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationVisionServiceAnalyzePosture),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *VisionServiceHTTPClientImpl) GetAnalysisJob(ctx context.Context, in *GetAnalysisJobRequest, opts ...http.CallOption) (*GetAnalysisJobResponse, error) {
	var out GetAnalysisJobResponse
	pattern := "/v1/vision/jobs/{job_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationVisionServiceGetAnalysisJob),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *VisionServiceHTTPClientImpl) RecognizeEquipment(ctx context.Context, in *RecognizeEquipmentRequest, opts ...http.CallOption) (*RecognizeEquipmentResponse, error) {
	var out RecognizeEquipmentResponse
	pattern := "/v1/vision/equipment:recognize"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationVisionServiceRecognizeEquipment),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
