// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vision/v1/vision.proto

package visionv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalysisType int32

const (
	AnalysisType_ANALYSIS_TYPE_UNSPECIFIED AnalysisType = 0
	AnalysisType_ANALYSIS_TYPE_EQUIPMENT   AnalysisType = 1
	AnalysisType_ANALYSIS_TYPE_POSTURE     AnalysisType = 2
)

// Enum value maps for AnalysisType.
var (
	AnalysisType_name = map[int32]string{
		0: "ANALYSIS_TYPE_UNSPECIFIED",
		1: "ANALYSIS_TYPE_EQUIPMENT",
		2: "ANALYSIS_TYPE_POSTURE",
	}
	AnalysisType_value = map[string]int32{
		"ANALYSIS_TYPE_UNSPECIFIED": 0,
		"ANALYSIS_TYPE_EQUIPMENT":   1,
		"ANALYSIS_TYPE_POSTURE":     2,
	}
)

func (x AnalysisType) Enum() *AnalysisType {
	p := new(AnalysisType)
	*p = x
	return p
}

func (x AnalysisType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnalysisType) Descriptor() protoreflect.EnumDescriptor {
	return file_vision_v1_vision_proto_enumTypes[0].Descriptor()
}

func (AnalysisType) Type() protoreflect.EnumType {
	return &file_vision_v1_vision_proto_enumTypes[0]
}

func (x AnalysisType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnalysisType.Descriptor instead.
func (AnalysisType) EnumDescriptor() ([]byte, []int) {
	return file_vision_v1_vision_proto_rawDescGZIP(), []int{0}
}

type AnalysisStatus int32

const (
	AnalysisStatus_ANALYSIS_STATUS_UNSPECIFIED AnalysisStatus = 0
	AnalysisStatus_ANALYSIS_STATUS_PENDING     AnalysisStatus = 1
	AnalysisStatus_ANALYSIS_STATUS_PROCESSING  AnalysisStatus = 2
	AnalysisStatus_ANALYSIS_STATUS_SUCCEEDED   AnalysisStatus = 3
	AnalysisStatus_ANALYSIS_STATUS_FAILED      AnalysisStatus = 4
)

// Enum value maps for AnalysisStatus.
var (
	AnalysisStatus_name = map[int32]string{
		0: "ANALYSIS_STATUS_UNSPECIFIED",
		1: "ANALYSIS_STATUS_PENDING",
		2: "ANALYSIS_STATUS_PROCESSING",
		3: "ANALYSIS_STATUS_SUCCEEDED",
		4: "ANALYSIS_STATUS_FAILED",
	}
	AnalysisStatus_value = map[string]int32{
		"ANALYSIS_STATUS_UNSPECIFIED": 0,
		"ANALYSIS_STATUS_PENDING":     1,
		"ANALYSIS_STATUS_PROCESSING":  2,
		"ANALYSIS_STATUS_SUCCEEDED":   3,
		"ANALYSIS_STATUS_FAILED":      4,
	}
)

func (x AnalysisStatus) Enum() *AnalysisStatus {
	p := new(AnalysisStatus)
	*p = x
	return p
}

func (x AnalysisStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnalysisStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_vision_v1_vision_proto_enumTypes[1].Descriptor()
}

func (AnalysisStatus) Type() protoreflect.EnumType {
	return &file_vision_v1_vision_proto_enumTypes[1]
}

func (x AnalysisStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnalysisStatus.Descriptor instead.
func (AnalysisStatus) EnumDescriptor() ([]byte, []int) {
	return file_vision_v1_vision_proto_rawDescGZIP(), []int{1}
}

type RecognizeEquipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUri      string                 `protobuf:"bytes,1,opt,name=image_uri,json=imageUri,proto3" json:"image_uri,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizeEquipmentRequest) Reset() {
	*x = RecognizeEquipmentRequest{}
	mi := &file_vision_v1_vision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizeEquipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeEquipmentRequest) ProtoMessage() {}

func (x *RecognizeEquipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vision_v1_vision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeEquipmentRequest.ProtoReflect.Descriptor instead.
func (*RecognizeEquipmentRequest) Descriptor() ([]byte, []int) {
	return file_vision_v1_vision_proto_rawDescGZIP(), []int{0}
}

func (x *RecognizeEquipmentRequest) GetImageUri() string {
	if x != nil {
		return x.ImageUri
	}
	return ""
}

func (x *RecognizeEquipmentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AnalyzePostureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoUri      string                 `protobuf:"bytes,1,opt,name=video_uri,json=videoUri,proto3" json:"video_uri,omitempty"`
	ExerciseCode  string                 `protobuf:"bytes,2,opt,name=exercise_code,json=exerciseCode,proto3" json:"exercise_code,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzePostureRequest) Reset() {
	*x = AnalyzePostureRequest{}
	mi := &file_vision_v1_vision_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzePostureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzePostureRequest) ProtoMessage() {}

func (x *AnalyzePostureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vision_v1_vision_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzePostureRequest.ProtoReflect.Descriptor instead.
func (*AnalyzePostureRequest) Descriptor() ([]byte, []int) {
	return file_vision_v1_vision_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzePostureRequest) GetVideoUri() string {
	if x != nil {
		return x.VideoUri
	}
	return ""
}

func (x *AnalyzePostureRequest) GetExerciseCode() string {
	if x != nil {
		return x.ExerciseCode
	}
	return ""
}

func (x *AnalyzePostureRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAnalysisJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalysisJobRequest) Reset() {
	*x = GetAnalysisJobRequest{}
	mi := &file_vision_v1_vision_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalysisJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalysisJobRequest) ProtoMessage() {}

func (x *GetAnalysisJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vision_v1_vision_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalysisJobRequest.ProtoReflect.Descriptor instead.
func (*GetAnalysisJobRequest) Descriptor() ([]byte, []int) {
	return file_vision_v1_vision_proto_rawDescGZIP(), []int{2}
}

func (x *GetAnalysisJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type RecognizeEquipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *AnalysisJob           `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizeEquipmentResponse) Reset() {
	*x = RecognizeEquipmentResponse{}
	mi := &file_vision_v1_vision_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizeEquipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeEquipmentResponse) ProtoMessage() {}

func (x *RecognizeEquipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vision_v1_vision_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeEquipmentResponse.ProtoReflect.Descriptor instead.
func (*RecognizeEquipmentResponse) Descriptor() ([]byte, []int) {
	return file_vision_v1_vision_proto_rawDescGZIP(), []int{3}
}

func (x *RecognizeEquipmentResponse) GetJob() *AnalysisJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type AnalyzePostureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *AnalysisJob           `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzePostureResponse) Reset() {
	*x = AnalyzePostureResponse{}
	mi := &file_vision_v1_vision_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzePostureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzePostureResponse) ProtoMessage() {}

func (x *AnalyzePostureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vision_v1_vision_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzePostureResponse.ProtoReflect.Descriptor instead.
func (*AnalyzePostureResponse) Descriptor() ([]byte, []int) {
	return file_vision_v1_vision_proto_rawDescGZIP(), []int{4}
}

func (x *AnalyzePostureResponse) GetJob() *AnalysisJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type GetAnalysisJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *AnalysisJob           `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalysisJobResponse) Reset() {
	*x = GetAnalysisJobResponse{}
	mi := &file_vision_v1_vision_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalysisJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalysisJobResponse) ProtoMessage() {}

func (x *GetAnalysisJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vision_v1_vision_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalysisJobResponse.ProtoReflect.Descriptor instead.
func (*GetAnalysisJobResponse) Descriptor() ([]byte, []int) {
	return file_vision_v1_vision_proto_rawDescGZIP(), []int{5}
}

func (x *GetAnalysisJobResponse) GetJob() *AnalysisJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type AnalysisJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Type          AnalysisType           `protobuf:"varint,2,opt,name=type,proto3,enum=vision.v1.AnalysisType" json:"type,omitempty"`
	Status        AnalysisStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=vision.v1.AnalysisStatus" json:"status,omitempty"`
	MediaUri      string                 `protobuf:"bytes,4,opt,name=media_uri,json=mediaUri,proto3" json:"media_uri,omitempty"`
	ResultJson    string                 `protobuf:"bytes,5,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisJob) Reset() {
	*x = AnalysisJob{}
	mi := &file_vision_v1_vision_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisJob) ProtoMessage() {}

func (x *AnalysisJob) ProtoReflect() protoreflect.Message {
	mi := &file_vision_v1_vision_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisJob.ProtoReflect.Descriptor instead.
func (*AnalysisJob) Descriptor() ([]byte, []int) {
	return file_vision_v1_vision_proto_rawDescGZIP(), []int{6}
}

func (x *AnalysisJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AnalysisJob) GetType() AnalysisType {
	if x != nil {
		return x.Type
	}
	return AnalysisType_ANALYSIS_TYPE_UNSPECIFIED
}

func (x *AnalysisJob) GetStatus() AnalysisStatus {
	if x != nil {
		return x.Status
	}
	return AnalysisStatus_ANALYSIS_STATUS_UNSPECIFIED
}

func (x *AnalysisJob) GetMediaUri() string {
	if x != nil {
		return x.MediaUri
	}
	return ""
}

func (x *AnalysisJob) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *AnalysisJob) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_vision_v1_vision_proto protoreflect.FileDescriptor

const file_vision_v1_vision_proto_rawDesc = "" +
	"\n" +
	"\x16vision/v1/vision.proto\x12\tvision.v1\x1a\x1cgoogle/api/annotations.proto\"Q\n" +
	"\x19RecognizeEquipmentRequest\x12\x1b\n" +
	"\timage_uri\x18\x01 \x01(\tR\bimageUri\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"r\n" +
	"\x15AnalyzePostureRequest\x12\x1b\n" +
	"\tvideo_uri\x18\x01 \x01(\tR\bvideoUri\x12#\n" +
	"\rexercise_code\x18\x02 \x01(\tR\fexerciseCode\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\".\n" +
	"\x15GetAnalysisJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"F\n" +
	"\x1aRecognizeEquipmentResponse\x12(\n" +
	"\x03job\x18\x01 \x01(\v2\x16.vision.v1.AnalysisJobR\x03job\"B\n" +
	"\x16AnalyzePostureResponse\x12(\n" +
	"\x03job\x18\x01 \x01(\v2\x16.vision.v1.AnalysisJobR\x03job\"B\n" +
	"\x16GetAnalysisJobResponse\x12(\n" +
	"\x03job\x18\x01 \x01(\v2\x16.vision.v1.AnalysisJobR\x03job\"\xe7\x01\n" +
	"\vAnalysisJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.vision.v1.AnalysisTypeR\x04type\x121\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.vision.v1.AnalysisStatusR\x06status\x12\x1b\n" +
	"\tmedia_uri\x18\x04 \x01(\tR\bmediaUri\x12\x1f\n" +
	"\vresult_json\x18\x05 \x01(\tR\n" +
	"resultJson\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage*e\n" +
	"\fAnalysisType\x12\x1d\n" +
	"\x19ANALYSIS_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ANALYSIS_TYPE_EQUIPMENT\x10\x01\x12\x19\n" +
	"\x15ANALYSIS_TYPE_POSTURE\x10\x02*\xa9\x01\n" +
	"\x0eAnalysisStatus\x12\x1f\n" +
	"\x1bANALYSIS_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ANALYSIS_STATUS_PENDING\x10\x01\x12\x1e\n" +
	"\x1aANALYSIS_STATUS_PROCESSING\x10\x02\x12\x1d\n" +
	"\x19ANALYSIS_STATUS_SUCCEEDED\x10\x03\x12\x1a\n" +
	"\x16ANALYSIS_STATUS_FAILED\x10\x042\x95\x03\n" +
	"\rVisionService\x12\x8c\x01\n" +
	"\x12RecognizeEquipment\x12$.vision.v1.RecognizeEquipmentRequest\x1a%.vision.v1.RecognizeEquipmentResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/vision/equipment:recognize\x12|\n" +
	"\x0eAnalyzePosture\x12 .vision.v1.AnalyzePostureRequest\x1a!.vision.v1.AnalyzePostureResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/vision/posture:analyze\x12w\n" +
	"\x0eGetAnalysisJob\x12 .vision.v1.GetAnalysisJobRequest\x1a!.vision.v1.GetAnalysisJobResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/vision/jobs/{job_id}B:Z8github.com/tiehu-ai/tiehu-fitness/api/vision/v1;visionv1b\x06proto3"

var (
	file_vision_v1_vision_proto_rawDescOnce sync.Once
	file_vision_v1_vision_proto_rawDescData []byte
)

func file_vision_v1_vision_proto_rawDescGZIP() []byte {
	file_vision_v1_vision_proto_rawDescOnce.Do(func() {
		file_vision_v1_vision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vision_v1_vision_proto_rawDesc), len(file_vision_v1_vision_proto_rawDesc)))
	})
	return file_vision_v1_vision_proto_rawDescData
}

var file_vision_v1_vision_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_vision_v1_vision_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_vision_v1_vision_proto_goTypes = []any{
	(AnalysisType)(0),                  // 0: vision.v1.AnalysisType
	(AnalysisStatus)(0),                // 1: vision.v1.AnalysisStatus
	(*RecognizeEquipmentRequest)(nil),  // 2: vision.v1.RecognizeEquipmentRequest
	(*AnalyzePostureRequest)(nil),      // 3: vision.v1.AnalyzePostureRequest
	(*GetAnalysisJobRequest)(nil),      // 4: vision.v1.GetAnalysisJobRequest
	(*RecognizeEquipmentResponse)(nil), // 5: vision.v1.RecognizeEquipmentResponse
	(*AnalyzePostureResponse)(nil),     // 6: vision.v1.AnalyzePostureResponse
	(*GetAnalysisJobResponse)(nil),     // 7: vision.v1.GetAnalysisJobResponse
	(*AnalysisJob)(nil),                // 8: vision.v1.AnalysisJob
}
var file_vision_v1_vision_proto_depIdxs = []int32{
	8, // 0: vision.v1.RecognizeEquipmentResponse.job:type_name -> vision.v1.AnalysisJob
	8, // 1: vision.v1.AnalyzePostureResponse.job:type_name -> vision.v1.AnalysisJob
	8, // 2: vision.v1.GetAnalysisJobResponse.job:type_name -> vision.v1.AnalysisJob
	0, // 3: vision.v1.AnalysisJob.type:type_name -> vision.v1.AnalysisType
	1, // 4: vision.v1.AnalysisJob.status:type_name -> vision.v1.AnalysisStatus
	2, // 5: vision.v1.VisionService.RecognizeEquipment:input_type -> vision.v1.RecognizeEquipmentRequest
	3, // 6: vision.v1.VisionService.AnalyzePosture:input_type -> vision.v1.AnalyzePostureRequest
	4, // 7: vision.v1.VisionService.GetAnalysisJob:input_type -> vision.v1.GetAnalysisJobRequest
	5, // 8: vision.v1.VisionService.RecognizeEquipment:output_type -> vision.v1.RecognizeEquipmentResponse
	6, // 9: vision.v1.VisionService.AnalyzePosture:output_type -> vision.v1.AnalyzePostureResponse
	7, // 10: vision.v1.VisionService.GetAnalysisJob:output_type -> vision.v1.GetAnalysisJobResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_vision_v1_vision_proto_init() }
func file_vision_v1_vision_proto_init() {
	if File_vision_v1_vision_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vision_v1_vision_proto_rawDesc), len(file_vision_v1_vision_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vision_v1_vision_proto_goTypes,
		DependencyIndexes: file_vision_v1_vision_proto_depIdxs,
		EnumInfos:         file_vision_v1_vision_proto_enumTypes,
		MessageInfos:      file_vision_v1_vision_proto_msgTypes,
	}.Build()
	File_vision_v1_vision_proto = out.File
	file_vision_v1_vision_proto_goTypes = nil
	file_vision_v1_vision_proto_depIdxs = nil
}
